--Author: ADDRMeridan

local AvionicData = {
--Intégrée
    ["Integrated"] = {
        ["Acier Ailé"] = {
            Description = "Augmente l'armure des archwings à proximité.",
            Image = "Acier Ailé.png",
            Manufacturer = {
                ["Lavan"] = {
                    InitialBonus = 0.06,
                    InitialDrain = 2,
                    MaxNaturalRank = 0,
                    Range = 90,
                },
                ["Vidar"] = {
                    InitialBonus = 0.05,
                    InitialDrain = 4,
                    MaxNaturalRank = 1,
                    Range = 60,
                },
                ["Zetki"] = {
                    InitialBonus = 0.45,
                    InitialDrain = 6,
                    MaxNaturalRank = 4,
                    Range = 100,
                },
            },
            Name = "Acier Ailé",
            NameEN = "Winged Steel",
            Target = "Archwing",
        },
        ["Amélioration Bricolée"] = {
            Description = "Réduit le temps de rechargement du tir Calamité.",
            Image = "Panel.png",
            Manufacturer = {
                ["Lavan"] = {
                    InitialBonus = 0.04,
                    InitialDrain = 4,
                    MaxNaturalRank = 4,
                },
                ["Vidar"] = {
                    InitialBonus = 0.05,
                    InitialDrain = 6,
                    MaxNaturalRank = 1,
                },
                ["Zetki"] = {
                    InitialBonus = 0.037,
                    InitialDrain = 10,
                    MaxNaturalRank = 7,
                },
            },
            Name = "Amélioration Bricolée",
            NameEN = "Ripload",
            Target = "Tir Calamité",
        },
        ["Bobine Polaire"] = {
            Description = "Augmente la capacité thermique des tourelles.",
            Image = "Panel.png",
            Manufacturer = {
                ["Lavan"] = {
                    InitialBonus = 0.07,
                    InitialDrain = 2,
                    MaxNaturalRank = 4,
                },
                ["Vidar"] = {
                    InitialBonus = 0.085,
                    InitialDrain = 2,
                    MaxNaturalRank = 1,
                },
                ["Zetki"] = {
                    InitialBonus = 0.06,
                    InitialDrain = 4,
                    MaxNaturalRank = 7,
                },
            },
            Name = "Bobine Polaire",
            NameEN = "Polar Coil",
            Target = "Tourelles",
        },
        ["Brûlure Ionique"] = {
            Description = "Augmente la vitesse de propulsion.",
            Image = "Panel.png",
            Manufacturer = {
                ["Lavan"] = {
                    InitialBonus = 0.036,
                    InitialDrain = 6,
                    MaxNaturalRank = 7,
                },
                ["Vidar"] = {
                    InitialBonus = 0.045,
                    InitialDrain = 4,
                    MaxNaturalRank = 1,
                },
                ["Zetki"] = {
                    InitialBonus = 0.042,
                    InitialDrain = 4,
                    MaxNaturalRank = 4,
                },
            },
            Name = "Brûlure Ionique",
            NameEN = "Ion Burn",
            Target = "Railjack",
        },
        ["Cartouche Ablative"] = {
            Description = "Réduit les dégâts chimiques.",
            Image = "Panel.png",
            Manufacturer = {
                ["Lavan"] = {
                    InitialBonus = 0.025,
                    InitialDrain = 2,
                    MaxNaturalRank = 0,
                },
                ["Vidar"] = {
                    InitialBonus = 0.04,
                    InitialDrain = 4,
                    MaxNaturalRank = 4,
                },
                ["Zetki"] = {
                    InitialBonus = 0.055,
                    InitialDrain = 4,
                    MaxNaturalRank = 4,
                },
            },
            Name = "Cartouche Ablative",
            NameEN = "Ablative Shell",
            Target = "Railjack",
        },
        ["Cellule d'Anode"] = {
            Description = "Augmente le rechargement de boucliers.",
            Image = "Cellule d'Anode.png",
            Manufacturer = {
                ["Lavan"] = {
                    InitialBonus = 0.06,
                    InitialDrain = 2,
                    MaxNaturalRank = 4,
                },
                ["Vidar"] = {
                    InitialBonus = 0.11,
                    InitialDrain = 2,
                    MaxNaturalRank = 1,
                },
                ["Zetki"] = {
                    InitialBonus = 0.07,
                    InitialDrain = 2,
                    MaxNaturalRank = 7,
                },
            },
            Name = "Cellule d'Anode",
            NameEN = "Anode Cell",
            Target = "Railjack",
        },
        ["Cloison"] = {
            Description = "Augmente la coque.",
            Image = "Cloison.png",
            Manufacturer = {
                ["Sigma"] = {
                    InitialBonus = 0.18,
                    InitialDrain = 2,
                    MaxNaturalRank = 1,    
                },
                ["Lavan"] = {
                    InitialBonus = 0.24,
                    InitialDrain = 4,
                    MaxNaturalRank = 1,
                },
                ["Vidar"] = {
                    InitialBonus = 0.32,
                    InitialDrain = 6,
                    MaxNaturalRank = 4,
                },
                ["Zetki"] = {
                    InitialBonus = 0.46,
                    InitialDrain = 10,
                    MaxNaturalRank = 7,
                },
            },
            Name = "Cloison",
            NameEN = "Bulkhead",
            Target = "Railjack",
        },
        ["Cyclone Ailé"] = {
            Description = "Augmente la vitesse des archwings à proximité.",
            Image = "Cyclone Ailé.png",
            Manufacturer = {
                ["Lavan"] = {
                    InitialBonus = 0.03125,
                    InitialDrain = 4,
                    MaxNaturalRank = 1,
                    Range = 90,
                },
                ["Vidar"] = {
                    InitialBonus = 0.03125,
                    InitialDrain = 2,
                    MaxNaturalRank = 4,
                    Range = 60,
                },
                ["Zetki"] = {
                    InitialBonus = 0.0272,
                    InitialDrain = 6,
                    MaxNaturalRank = 7,
                    Range = 100,
                },
            },
            Name = "Cyclone Ailé",
            NameEN = "Winged Cyclone",
            Target = "Archwing",
        },
        ["Densité de Section"] = {
            Description = "Augmente les dégâts critiques de toutes les tourelles.",
            Image = "Densitedesection.png",
            Manufacturer = {
                ["Lavan"] = {
                    InitialBonus = 0.085,
                    InitialDrain = 2,
                    MaxNaturalRank = 1,
                },
                ["Vidar"] = {
                    InitialBonus = 0.08,
                    InitialDrain = 4,
                    MaxNaturalRank = 4,
                },
                ["Zetki"] = {
                    InitialBonus = 0.07,
                    InitialDrain = 6,
                    MaxNaturalRank = 7,
                },
            },
            Name = "Densité de Section",
            NameEN = "Section Density",
            Target = "Tourelles",
        },
        ["Dernier Combat"] = {
            Description = "Augmente les dégâts de toutes les tourelles quand l'état de la coque est sous les 20%.",
            Image = "Panel.png",
            Manufacturer = {
                ["Lavan"] = {
                    InitialBonus = 0.19,
                    InitialDrain = 2,
                    MaxNaturalRank = 0,
                },
                ["Vidar"] = {
                    InitialBonus = 0.23,
                    InitialDrain = 4,
                    MaxNaturalRank = 0,
                },
                ["Zetki"] = {
                    InitialBonus = 0.19,
                    InitialDrain = 6,
                    MaxNaturalRank = 4,
                },
            },
            Name = "Dernier Combat",
            NameEN = "Last Stand",
            Target = "Tourelles",
        },
        ["Dissipateur de Chaleur"] = {
            Description = "Réduit les dégâts incendiaires.",
            Image = "Panel.png",
            Manufacturer = {
                ["Lavan"] = {
                    InitialBonus = 0.05,
                    InitialDrain = 2,
                    MaxNaturalRank = 0,
                },
                ["Vidar"] = {
                    InitialBonus = 0.07,
                    InitialDrain = 4,
                    MaxNaturalRank = 4,
                },
                ["Zetki"] = {
                    InitialBonus = 0.08,
                    InitialDrain = 6,
                    MaxNaturalRank = 1,
                },
            },
            Name = "Dissipateur de Chaleur",
            NameEN = "Heat Sink",
            Target = "Railjack",
        },
        ["Force Ailé"] = {
            Description = "Augmente les boucliers des archwings à proximité.",
            Image = "Panel.png",
            Manufacturer = {
                ["Lavan"] = {
                    InitialBonus = 0.05,
                    InitialDrain = 4,
                    MaxNaturalRank = 0,
                    Range = 96,
                },
                ["Vidar"] = {
                    InitialBonus = 0.038,
                    InitialDrain = 4,
                    MaxNaturalRank = 1,
                    Range = 64,
                },
                ["Zetki"] = {
                    InitialBonus = 0.03125,
                    InitialDrain = 4,
                    MaxNaturalRank = 4,
                    Range = 100,
                },
            },
            Name = "Force Ailé",
            NameEN = "Winged Force",
            Target = "Archwing",
        },
        ["Hyperflux"] = {
            Description = "???",
            Image = "Panel.png",
            Manufacturer = {
                ["Lavan"] = {
                    InitialBonus = 0.09,
                    InitialDrain = 6,
                    MaxNaturalRank = 1,
                },
                ["Vidar"] = {
                    InitialBonus = 0.07,
                    InitialDrain = 4,
                    MaxNaturalRank = 4,
                },
                ["Zetki"] = {
                    InitialBonus = 0.09,
                    InitialDrain = 10,
                    MaxNaturalRank = 7,
                },
            },
            Name = "Hyperflux",
            NameEN = "Hyperflux",
            Target = "Railjack",
        },
        ["Hyperstrike"] = {
            Description = "Augmente les dégâts des tourelles.",
            Image = "Panel.png",
            Manufacturer = {
                ["Sigma"] = {
                    InitialBonus = 0.08,
                    InitialDrain = 4,
                    MaxNaturalRank = 1,
                },
                ["Lavan"] = {
                    InitialBonus = 0.095,
                    InitialDrain = 4,
                    MaxNaturalRank = 4,
                },
                ["Vidar"] = {
                    InitialBonus = 0.092,
                    InitialDrain = 6,
                    MaxNaturalRank = 7,
                },
                ["Zetki"] = {
                    InitialBonus = 0.11,
                    InitialDrain = 6,
                    MaxNaturalRank = 7,
                },
            },
            Name = "Hyperstrike",
            NameEN = "Hyperstrike",
            Target = "Tourelles",
        },
        ["Jet Conique"] = {
            Description = "Augmente la vitesse.",
            Image = "Panel.png",
            Manufacturer = {
                ["Lavan"] = {
                    InitialBonus = 0.023,
                    InitialDrain = 6,
                    MaxNaturalRank = 7,
                },
                ["Vidar"] = {
                    InitialBonus = 0.02,
                    InitialDrain = 4,
                    MaxNaturalRank = 1,
                },
                ["Zetki"] = {
                    InitialBonus = 0.024,
                    InitialDrain = 10,
                    MaxNaturalRank = 4,
                },
            },
            Name = "Jet Conique",
            NameEN = "Conic Nozzle",
            Target = "Railjack",
        },
        ["Maxima"] = {
            Description = "Augmente les boucliers max.",
            Image = "Panel.png",
            Manufacturer = {
                ["Lavan"] = {
                    InitialBonus = 0.06,
                    InitialDrain = 4,
                    MaxNaturalRank = 4,
                },
                ["Vidar"] = {
                    InitialBonus = 0.07,
                    InitialDrain = 4,
                    MaxNaturalRank = 4,
                },
                ["Zetki"] = {
                    InitialBonus = 0.065,
                    InitialDrain = 6,
                    MaxNaturalRank = 7,
                },
            },
            Name = "Maxima",
            NameEN = "Maxima",
            Target = "Railjack",
        },
        ["Ogive"] = {
            Description = "Augmente les dégâts du tir Calamité.",
            Image = "Panel.png",
            Link = "Ogive (Avionique)",
            Manufacturer = {
                ["Lavan"] = {
                    InitialBonus = 0.07,
                    InitialDrain = 4,
                    MaxNaturalRank = 4,
                },
                ["Vidar"] = {
                    InitialBonus = 0.055,
                    InitialDrain = 6,
                    MaxNaturalRank = 7,
                },
                ["Zetki"] = {
                    InitialBonus = 0.065,
                    InitialDrain = 10,
                    MaxNaturalRank = 7,
                },
            },
            Name = "Ogive",
            NameEN = "Warhead (Avionic)",
            Target = "Tir Calamité",
        },
        ["Pièce Principale"] = {
            Description = "Augmente les dégâts de la pièce principale.",
            Image = "Panel.png",
            Manufacturer = {
                ["Lavan"] = {
                    InitialBonus = 0.065,
                    InitialDrain = 4,
                    MaxNaturalRank = 1,
                },
                ["Vidar"] = {
                    InitialBonus = 0.055,
                    InitialDrain = 6,
                    MaxNaturalRank = 4,
                },
                ["Zetki"] = {
                    InitialBonus = 0.085,
                    InitialDrain = 6,
                    MaxNaturalRank = 7,
                },
            },
            Name = "Pièce Principale",
            NameEN = "Forward Artillery",
            Target = "Railjack",
        },
        ["Prédateur"] = {
            Description = "Augmente les chances de critique de toutes les tourelles.",
            Image = "Panel.png",
            Manufacturer = {
                ["Lavan"] = {
                    InitialBonus = 0.01,
                    InitialDrain = 2,
                    MaxNaturalRank = 0,
                },
                ["Vidar"] = {
                    InitialBonus = 0.095,
                    InitialDrain = 2,
                    MaxNaturalRank = 1,
                },
                ["Zetki"] = {
                    InitialBonus = 0.09,
                    InitialDrain = 4,
                    MaxNaturalRank = 4,
                },
            },
            Name = "Prédateur",
            NameEN = "Predator",
            Target = "Tourelles",
        },
        ["Tempête Ailée"] = {
            Description = "Augmente les dégâts des archwings à proximité.",
            Image = "Panel.png",
            Manufacturer = {
                ["Lavan"] = {
                    InitialBonus = 0.03,
                    InitialDrain = 4,
                    MaxNaturalRank = 1,
                    Range = 90,
                },
                ["Vidar"] = {
                    InitialBonus = 0.02,
                    InitialDrain = 4,
                    MaxNaturalRank = 4,
                    Range = 60,
                },
                ["Zetki"] = {
                    InitialBonus = 0.0181,
                    InitialDrain = 4,
                    MaxNaturalRank = 7,
                    Range = 100,
                },
            },
            Name = "Tempête Ailée",
            NameEN = "Winged Storm",
            Target = "Archwing",
        },
        ["Thermatique"] = {
            Description = "Réduit les dégâts de givre.",
            Image = "Panel.png",
            Manufacturer = {
                ["Lavan"] = {
                    InitialBonus = 0.065,
                    InitialDrain = 2,
                    MaxNaturalRank = 0,
                },
                ["Vidar"] = {
                    InitialBonus = 0.055,
                    InitialDrain = 4,
                    MaxNaturalRank = 4,
                },
                ["Zetki"] = {
                    InitialBonus = 0.04,
                    InitialDrain = 6,
                    MaxNaturalRank = 4,
                },
            },
            Name = "Thermatique",
            NameEN = "Thermatic",
            Target = "Railjack",
        },
        ["Tissage de Coque"] = {
            Description = "Augmente l'armure max.",
            Image = "Panel.png",
            Manufacturer = {
                ["Sigma"] = {
                    InitialBonus = 0.07,
                    InitialDrain = 2,
                    MaxNaturalRank = 1,
                },
                ["Lavan"] = {
                    InitialBonus = 0.14,
                    InitialDrain = 4,
                    MaxNaturalRank = 1,
                },
                ["Vidar"] = {
                    InitialBonus = 0.27,
                    InitialDrain = 4,
                    MaxNaturalRank = 4,
                },
                ["Zetki"] = {
                    InitialBonus = 0.23,
                    InitialDrain = 6,
                    MaxNaturalRank = 7,
                },
            },
            Name = "Tissage de Coque",
            NameEN = "Hull Weave",
            Target = "Railjack",
        },
        ["Tissage de Phase"] = {
            Description = "Réduit les dégâts ioniques.",
            Image = "Panel.png",
            Manufacturer = {
                ["Lavan"] = {
                    InitialBonus = 0.055,
                    InitialDrain = 2,
                    MaxNaturalRank = 0,
                },
                ["Vidar"] = {
                    InitialBonus = 0.045,
                    InitialDrain = 4,
                    MaxNaturalRank = 7,
                },
                ["Zetki"] = {
                    InitialBonus = 0.05,
                    InitialDrain = 6,
                    MaxNaturalRank = 4,
                },
            },
            Name = "Tissage de Phase",
            NameEN = "Phasic Weave",
            Target = "Railjack",
        },
    },
--Stratégique
    ["Tactical"] = {
        ["Brèche Quanta"] = {
            BonusTitle = nil,
            BonusScale = nil,
            BonusValues = nil,
            Cooldown = 300,
            Description = "Stabilise temporairement les brèches de la coque.",
            DurationScale = 5,
            DurationValues = nil,
            Image = "Panel.png",
            InitialBonus = nil,
            InitialDuration = 20,
            InitialDrain = 4,
            MaxNaturalRank = 4,
            Name = "Brèche Quanta",
            NameEN = "Breach Quanta",
        },
        ["Champs de Tir"] = {
            BonusTitle = nil,
            BonusScale = nil,
            BonusValues = nil,
            Cooldown = 300,
            Description = "Retire temporairement tout les temps de rechargement des tourelles.",
            DurationScale = nil,
            DurationValues = {15, 17, 20, 23, 25, 27, 30},
            Image = "Panel.png",
            InitialBonus = nil,
            InitialDuration = 10,
            InitialDrain = 6,
            MaxNaturalRank = 4,
            Name = "Champs de Tir",
            NameEN = "Death Blossom",
        },
        ["Flux Brûlant"] = {
            BonusTitle = "Bonus de Vitesse (%)",
            BonusScale = nil,
            BonusValues = {15, 17, 20, 23, 25, 28, 30, 30, 30, 30},
            Cooldown = 240,
            Description = "Augmente temporairement la vitesse de base et de propulsion.",
            DurationScale = nil,
            DurationValues = {5, 6, 6, 7, 7, 8, 9, 10, 10, 10, 10},
            Image = "Fluxbrulant.png",
            InitialBonus = 12,
            InitialDuration = 5,
            InitialDrain = 6,
            MaxNaturalRank = 7,
            Name = "Flux Brûlant",
            NameEN = "Flow Burn",
        },
        ["Forge de Combat"] = {
            BonusTitle = nil,
            BonusScale = nil,
            BonusValues = nil,
            Cooldown = 480,
            Description = "Réduit le temps de rechargement des forges.",
            DurationScale = nil,
            DurationValues = {35, 40, 60, 80, 100, 110, 120},
            Image = "Forge de Combat.png",
            InitialBonus = nil,
            InitialDuration = 30,
            InitialDrain = 4,
            MaxNaturalRank = 4,
            Name = "Forge de Combat",
            NameEN = "Battle Forge",
        },
        ["Rassemblement"] = {
            BonusTitle = "Soin (%)",
            BonusScale = nil,
            BonusValues = {35, 45, 55, 65, 75, 85, 100},
            Cooldown = 240,
            Description = "Rappelle tous les membres de l'équipage au Railjack et les soigne.",
            DurationScale = nil,
            DurationValues = nil,
            Image = "Rassemblement.png",
            InitialBonus = 25,
            InitialDuration = nil,
            InitialDrain = 6,
            MaxNaturalRank = 4,
            Name = "Rassemblement",
            NameEN = "Form Up",
        },
        ["Régénération d'Escouade"] = {
            BonusTitle = "Soin (%)",
            BonusScale = nil,
            BonusValues = {55, 60, 65, 70, 75, 80, 100},
            Cooldown = 300,
            Description = "Soigne tous les membres de l'équipage du Railjack.",
            DurationScale = nil,
            DurationValues = nil,
            Image = "Panel.png",
            InitialBonus = 50,
            InitialDuration = nil,
            InitialDrain = 6,
            MaxNaturalRank = 4,
            Name = "Régénération d'Escouade",
            NameEN = "Squad Renew",
        },
        ["Stase d'Intrus"] = {
            BonusTitle = nil,
            BonusScale = nil,
            BonusValues = nil,
            Cooldown = 300,
            Description = "Immobilise temporairement tout les ennemis à bord du Railjack.",
            DurationScale = 5,
            DurationValues = nil,
            Image = "Stase d'Intrus.png",
            InitialBonus = nil,
            InitialDuration = 10,
            InitialDrain = 6,
            MaxNaturalRank = 4,
            Name = "Stase d'Intrus",
            NameEN = "Intruder Stasis",
        },
        ["Stations de Combat"] = {
            BonusTitle = "Dégâts (%)",
            BonusScale = nil,
            BonusValues = {30, 50, 55, 60, 65, 70, 75},
            Cooldown = 240,
            Description = "Augmentation temporaire des dégâts des tourelles.",
            DurationScale = 2,
            DurationValues = nil,
            Image = "Panel.png",
            InitialBonus = 20,
            InitialDuration = 16,
            InitialDrain = 6,
            MaxNaturalRank = 4,
            Name = "Stations de Combat",
            NameEN = "Battle Stations",
        },
        ["Suppression d'Incendie"] = {
            BonusTitle = "Nbr. d'Incidents",
            BonusScale = 1,
            BonusValues = nil,
            Cooldown = 300,
            Description = "Eteint un certain nombre d'incendies ou de failles électriques.",
            DurationScale = nil,
            DurationValues = nil,
            Image = "Suppression d'Incendie.png",
            InitialBonus = 1,
            InitialDuration = nil,
            InitialDrain = 4,
            MaxNaturalRank = 4,
            Name = "Suppression d'Incendie",
            NameEN = "Fire Suppression",
        },
        ["Voile du Néant"] = {
            BonusTitle = "Ralentissement (%)",
            BonusScale = nil,
            BonusValues = {10, 15, 20, 25, 30, 35, 50},
            Cooldown = 120,
            Description = "Rend le Railjack temporairement invisible au détriment de sa vitesse.",
            DurationScale = nil,
            DurationValues = {15, 20, 25, 30, 35, 40, 50},
            Image = "Panel.png",
            InitialBonus = 5,
            InitialDuration = 10,
            InitialDrain = 6,
            MaxNaturalRank = 4,
            Name = "Voile du Néant",
            NameEN = "Void Cloak",
        },
    },
--De Combat
    ["Battle"] = {
        ["Bélier à Particules"] = {
            Bonus = {
                {
                    BonusScale = 200,
                    BonusValues = nil,
                    InitialBonus = 100,
                    Name = "Dégâts",
                    Unit = nil,
                },
                {
                    BonusScale = nil,
                    BonusValues = {2.5, 3, 3.5, 4, 4.5, 5, 6},
                    InitialBonus = 2,
                    Name = "Durée Projection",
                    Unit = "s",
                },
            },
            Description = "Déploie un bélier à particules infligeant X dégâts/s. Désactiver pour projeter le bélier pendant Xs.",
            Image = "Belieraparticule.png",
            InitialDrain = 4,
            MaxNaturalRank = 4,
            Name = "Bélier à Particules",
            NameEN  = "Particle Ram",
            Slot = 2,
        },
        ["Contre-mesures"] = {
            Bonus = {
                {
                    BonusScale = nil,
                    BonusValues = {12, 14, 18, 20, 24, 26, 32},
                    InitialBonus = 10,
                    Name = "Leurres Produit",
                    Unit = nil,
                },
            },
            Description = "Déploie X fusées éclairantes détournant les projectiles guidés ennemis.",
            Image = "Contre-mesures.png",
            InitialDrain = 2,
            MaxNaturalRank = 4,
            Name = "Contre-mesures",
            NameEN  = "Countermeasures",
            Slot = 1,
        },
        ["Explosion Éclatante"] = {
            Bonus = {
                {
                    BonusScale = nil,
                    BonusValues = {300, 400, 300, 400, 300, 400, 500},
                    InitialBonus = 200,
                    Name = "Dégâts",
                    Unit = nil,
                },
                {
                    BonusScale = 0.5,
                    BonusValues = nil,
                    InitialBonus = 3.5,
                    Name = "Explosions/s",
                    Unit = nil,
                },
                {
                    BonusScale = nil,
                    BonusValues = {10, 10, 12, 14, 16, 18, 20},
                    InitialBonus = 10,
                    Name = "Durée",
                    Unit = "s",
                },
                {
                    BonusScale = 5,
                    BonusValues = nil,
                    InitialBonus = 20,
                    Name = "Portée",
                    Unit = "m",
                },
            },
            Description = "Crée un barrage de X explosions/s sur Xs, infligeant X de dégâts dans un rayon de Xm.",
            Image = "Explosioneclatante.png",
            InitialDrain = 4,
            MaxNaturalRank = 4,
            Name = "Explosion Éclatante",
            NameEN  = "Shatter Burst",
            Slot = 2,
        },
        ["Grelin"] = {
            Bonus = {
                {
                    BonusScale = nil,
                    BonusValues = {3, 4, 5, 6, 7, 8, 10},
                    InitialBonus = 2,
                    Name = "Nbr. Cibles",
                    Unit = nil,
                },
                {
                    BonusScale = nil,
                    BonusValues = {100, 110, 120, 140, 160, 180, 200},
                    InitialBonus = 75,
                    Name = "Portée Champ",
                    Unit = "m",
                },
                {
                    BonusScale = nil,
                    BonusValues = {12, 13, 14, 15, 16, 18, 20},
                    InitialBonus = 8,
                    Name = "Durée",
                    Unit = "s",
                },
                {
                    BonusScale = nil,
                    BonusValues = {1200, 1400, 1600, 1800, 2000, 2500, 3000},
                    InitialBonus = 1000,
                    Name = "Dégâts Explosion",
                    Unit = nil,
                },
                {
                    BonusScale = nil,
                    BonusValues = {50, 65, 75, 85, 95, 100, 220},
                    InitialBonus = 50,
                    Name = "Portée Explosion",
                    Unit = "m",
                },
            },
            Description = "Émet un champ qui restreint les mouvements de X cibles ennemies dans les Xm pendant Xs. Détone en infligeant X dégâts sur Xm.",
            Image = "Grelin.png",
            InitialDrain = 4,
            MaxNaturalRank = 4,
            Name = "Grelin",
            NameEN  = "Tether",
            Slot = 2,
        },
        ["Phénix Enragé"] = {
            Bonus = {
                {
                    BonusScale = nil,
                    BonusValues = {150, 175, 200, 225, 250, 275, 300},
                    InitialBonus = 100,
                    Name = "Dégâts/s Trace",
                    Unit = nil,  
                },
                {
                    BonusScale = nil,
                    BonusValues = {5, 7, 10, 12, 15, 18, 20},
                    InitialBonus = 3,
                    Name = "Bonus Vitesse",
                    Unit = "+%",  
                },
                {
                    BonusScale = nil,
                    BonusValues = {15, 20, 22, 24, 26, 28, 30},
                    InitialBonus = 10,
                    Name = "Réduction Dégâts",
                    Unit = "%",  
                },
                {
                    BonusScale = nil,
                    BonusValues = {40, 50, 60, 70, 80, 90, 100},
                    InitialBonus = 25,
                    Name = "Dégâts Accumulés/s",
                    Unit = nil,  
                },
                {
                    BonusScale = 25,
                    BonusValues = nil,
                    InitialBonus = 100,
                    Name = "Rayon Explosion",
                    Unit = "m",  
                },
            },
            Description = "Laisse une trace de feu infligeant X dégâts par seconde aux ennemis. Obtenez X% en vitesse et X% de réductions aux dégâts lorsqu'actif. Accumule X dégâts/s relâchés sur Xm lorsque désactivé.",
            Image = "Phenixenrage.png",
            InitialDrain = 6,
            MaxNaturalRank = 4,
            Name = "Phénix Enragé",
            NameEN  = "Fiery Phoenix",
            Slot = 3,
        },
        ["Impulsion Atonique"] = {
            Bonus = {
                {
                    BonusScale = nil,
                    BonusValues = {125, 150, 175, 200, 225, 250, 300},
                    InitialBonus = 100,
                    Name = "Dégâts",
                    Unit = nil,  
                },
                {
                    BonusScale = 0,
                    BonusValues = nil,
                    InitialBonus = 100,
                    Name = "Rayon Désactivation",
                    Unit = "m",  
                },
                {
                    BonusScale = nil,
                    BonusValues = {180, 180, 180, 190, 200, 230, 250},
                    InitialBonus = 150,
                    Name = "Rayon Explosion",
                    Unit = "m",  
                },
            },
            Description = "Déploie une impulsion électromagnétique, infligeant X de dégâts aux ennemis à moins de 100m de distance, les incapacitant temporairement. Détoner manuellement permet d'agrandir le rayon de l'explosion à Xm.",
            Image = "Impulsionatonique.png",
            InitialDrain = 4,
            MaxNaturalRank = 4,
            Name = "Impulsion Atonique",
            NameEN  = "Blackout Pulse",
            Slot = 1,
        },
        ["Salve de Missiles"] = {
            Bonus = {
                {
                    BonusScale = nil,
                    BonusValues = {20, 24, 30, 34, 38, 44, 50},
                    InitialBonus = 16,
                    Name = "Nbr. Missiles",
                    Unit = nil,
                },
            },
            Description = "Tire X missiles à tête chercheuse.",
            Image = "Salve de Missiles.png",
            InitialDrain = 6,
            MaxNaturalRank = 4,
            Name = "Salve de Missiles",
            NameEN  = "Seeker Volley",
            Slot = 3,
        },
        ["Trou du Néant"] = {
            Bonus = {
                {
                    BonusScale = nil,
                    BonusValues = {210, 220, 230, 240, 250, 280, 300},
                    InitialBonus = 200,
                    Name = "Dégâts/s",
                    Unit = nil,
                },
                {
                    BonusScale = nil,
                    BonusValues = {10, 13, 15, 17, 20, 23, 25},
                    InitialBonus = 8,
                    Name = "Durée",
                    Unit = "s",
                },
                {
                    BonusScale = nil,
                    BonusValues = {90, 100, 110, 120, 130, 140, 150},
                    InitialBonus = 75,
                    Name = "Rayon",
                    Unit = "m",
                },
            },
            Description = "Crée un trou noir de Xm aspirant les ennemis et leur infligeant X dégâts/s pendant Xs.",
            Image = "Trouduneant.png",
            InitialDrain = 6,
            MaxNaturalRank = 4,
            Name = "Trou du Néant",
            NameEN  = "Void Hole",
            Slot = 3,
        },
        ["Vortex de Munitions"] = {
            Bonus = {
                {
                    BonusScale = nil,
                    BonusValues = {5, 8, 9, 10, 12, 14, 15},
                    InitialBonus = 5,
                    Name = "Durée",
                    Unit = "s",
                },
                {
                    BonusScale = nil,
                    BonusValues = {75, 85, 100, 120, 130, 140, 150},
                    InitialBonus = 50,
                    Name = "Rayon",
                    Unit = "m",
                },
            },
            Description = "Déploie une bulle absorbant les tirs ennemis pendant Xs. Détone tous les dégâts accumulés sur une distance de Xm.",
            Image = "Vortexdemunitions.png",
            InitialDrain = 2,
            MaxNaturalRank = 4,
            Name = "Vortex de Munitions",
            NameEN  = "Munitions Vortex",
            Slot = 1,
        },
    },
}

return AvionicData