--Author: ADDRMeridan

local AvionicData = {
    --Intégrée
            ["Acier Ailé"] = {
                Description = "Augmente l'armure des archwings à proximité.",
                Image = "Acier Ailé.png",
                Manufacturer = "Zetki",
                Name = "Acier Ailé",
                NameEN = "Winged Steel",
                Rarity = "Inhabituelle",
                Target = "Archwing",
                Type = "Integrated",
            },
            ["Amélioration Bricolée"] = {
                Description = "Réduit le temps de rechargement du tir Calamité.",
                Image = "Amélioration Bricolée.png",
                Manufacturer = "Lavan",
                Name = "Amélioration Bricolée",
                NameEN = "Ripload",
                Rarity = "Commune",
                Target = "Tir Calamité",
                Type = "Integrated",
            },
            ["Artillerie Facile"] = {
                Description = "Donne une chance à la Pièce Principale de ne pas consommer une Charge du Dôme.",
                Image = "Artillerie_Facile.png",
                Manufacturer = "Zetki",
                Name = "Artillerie Facile",
                NameEN = "Artillery Cheap Shot",
                Rarity = "Commune",
                Target = "Artillerie",
                Type = "Integrated",
            },
            ["Bobine Polaire"] = {
                Description = "Augmente la capacité thermique des tourelles.",
                Image = "Bobine Polaire.png",
                Introduced = "27.0.0",
                Manufacturer = "Vidar",
                Name = "Bobine Polaire",
                NameEN = "Polar Coil",
                Rarity = "Commune",
                Target = "Tourelles",
                Type = "Integrated",
            },
            ["Brûlure Ionique"] = {
                Description = "Augmente la vitesse de propulsion.",
                Image = "Brûlure Ionique.png",
                Manufacturer = "Zetki",
                Name = "Brûlure Ionique",
                NameEN = "Ion Burn",
                Rarity = "Rare",
                Target = "Moteurs",
                Type = "Integrated",
            },
            ["Calamité Facile"] = {
                Description = "Donne une chance au tir Calamité de ne pas consommer de munitions.",
                Image = "Calamité Facile.png",
                Manufacturer = "Lavan",
                Name = "Calamité Facile",
                NameEN = "Ordnance Cheap Shot",
                Rarity = "Rare",
                Target = "Tir Calamité",
                Type = "Integrated",
            },
            ["Cellule d'Anode"] = {
                Description = "Augmente le rechargement de boucliers.",
                Image = "Cellule d'Anode.png",
                Manufacturer = "Zetki",
                Name = "Cellule d'Anode",
                NameEN = "Anode Cell",
                Rarity = "Rare",
                Target = "Boucliers",
                Type = "Integrated",
            },
            ["Cloison"] = {
                Description = "Augmente la coque.",
                Image = "Cloison.png",
                Manufacturer = "Vidar",
                Name = "Cloison",
                NameEN = "Bulkhead",
                Rarity = "Inhabituelle",
                Target = "Coque",
                Type = "Integrated",
            },
            ["Courage Sentient"] = {
                Description = "Réduit les dégâts infligés des ennemis Sentient aux boucliers du Railjack.",
                Image = "Courage Sentient.png",
                Manufacturer = "Lavan",
                Name = "Courage Sentient",
                NameEN = "Sentient Fortitude",
                Rarity = "Rare",
                Target = "Boucliers",
                Type = "Integrated",
            },
            ["Cyclone Ailé"] = {
                Description = "Augmente la vitesse des archwings à proximité.",
                Image = "Cyclone Ailé.png",
                Manufacturer = "Zetki",
                Name = "Cyclone Ailé",
                NameEN = "Winged Cyclone",
                Rarity = "Rare",
                Target = "Archwing",
                Type = "Integrated",
            },
            ["Densité de Section"] = {
                Description = "Augmente les dégâts critiques de toutes les tourelles.",
                Image = "Densité de Section.png",
                Manufacturer = "Vidar",
                Name = "Densité de Section",
                NameEN = "Section Density",
                Rarity = "Rare",
                Target = "Tourelles",
                Type = "Integrated",
            },
            ["Dernier Combat"] = {
                Description = "Augmente les dégâts de toutes les tourelles quand l'état de la coque est sous les 20%.",
                Image = "Dernier Combat.png",
                Manufacturer = "Zetki",
                Name = "Dernier Combat",
                NameEN = "Last Stand",
                Rarity = "Inhabituelle",
                Target = "Tourelles",
                Type = "Integrated",
            },
            ["Dissipateur de Chaleur"] = {
                Description = "Réduit les dégâts [[File:Incendiaire.png|20px]] Incendiaires.",
                Image = "Dissipateur de Chaleur.png",
                Manufacturer = "Lavan",
                Name = "Dissipateur de Chaleur",
                NameEN = "Heat Sink",
                Rarity = "Commune",
                Target = "Élémentaire",
                Type = "Integrated",
            },
            ["Éco-Revo"] = {
                Description = "Réduit tous les coûts de Révolite.",
                Image = "Éco-Revo.png",
                Manufacturer = "Lavan",
                Name = "Éco-Revo",
                NameEN = "Revo Reducer",
                Rarity = "Rare",
                Target = "Forge",
                Type = "Integrated",
            },
            ["Force Ailé"] = {
                Description = "Augmente les boucliers des Archwings à proximité.",
                Image = "Force Ailé.png",
                Manufacturer = "Zetki",
                Name = "Force Ailé",
                NameEN = "Winged Force",
                Rarity = "Inhabituelle",
                Target = "Archwing",
                Type = "Integrated",
            },
            ["Hyperflux"] = {
                Description = "Augmente l'Énergie Flux.",
                Image = "Hyperflux.png",
                Manufacturer = "Lavan",
                Name = "Hyperflux",
                NameEN = "Hyperflux",
                Rarity = "Rare",
                Target = "Forge",
                Type = "Integrated",
            },
            ["Hyperstrike"] = {
                Description = "Augmente les dégâts des tourelles.",
                Image = "Hyperstrike.png",
                Manufacturer = "Vidar",
                Name = "Hyperstrike",
                NameEN = "Hyperstrike",
                Rarity = "Rare",
                Target = "Tourelles",
                Type = "Integrated",
            },
            ["Jet Conique"] = {
                Description = "Augmente la vitesse.",
                Image = "Jet Conique.png",
                Manufacturer = "Zetki",
                Name = "Jet Conique",
                NameEN = "Conic Nozzle",
                Rarity = "Rare",
                Target = "Moteurs",
                Type = "Integrated",
            },
            ["Maxima"] = {
                Description = "Augmente les boucliers max.",
                Image = "Maxima.png",
                Manufacturer = "Zetki",
                Name = "Maxima",
                NameEN = "Maxima",
                Rarity = "Rare",
                Target = "Boucliers",
                Type = "Integrated",
            },
            ["Montée d'Adrénaline"] = {
                Description = "Augmente la vitesse de régénération des boucliers du Railjack pendant une brèche de la coque.",
                Image = "Montée d'Adrénaline.png",
                Manufacturer = "Lavan",
                Name = "Montée d'Adrénaline",
                NameEN = "Breach Adrenaline",
                Rarity = "Rare",
                Target = "Boucliers",
                Type = "Integrated",
            },
            ["Ogive"] = {
                Description = "Augmente les dégâts du tir Calamité.",
                Image = "Ogive.png",
                Link = "Ogive (Avionique)",
                Manufacturer = "Lavan",
                Name = "Ogive",
                NameEN = "Warhead (Avionic)",
                Rarity = "Inhabituelle",
                Target = "Tir Calamité",
                Type = "Integrated",
            },
            ["Pièce Principale"] = {
                Description = "Augmente les dégâts de la Pièce Principale.",
                Image = "Pièce Principale.png",
                Manufacturer = "Zetki",
                Name = "Pièce Principale",
                NameEN = "Forward Artillery",
                Rarity = "Rare",
                Target = "Artillerie",
                Type = "Integrated",
            },
            ["Prédateur"] = {
                Description = "Augmente les Chances de Critique de toutes les tourelles.",
                Image = "Prédateur.png",
                Manufacturer = "Vidar",
                Name = "Prédateur",
                NameEN = "Predator",
                Rarity = "Rare",
                Target = "Tourelles",
                Type = "Integrated",
            },
            ["Revêtement Ablatif"] = {
                Description = "Réduit les dégâts [[File:Chimique.png|20px]] Chimique.",
                Image = "Revêtement Ablatif.png",
                Manufacturer = "Lavan",
                Name = "Revêtement Ablatif",
                NameEN = "Ablative Shell",
                Rarity = "Commune",
                Target = "Élémentaire",
                Type = "Integrated",
            },
            ["Scalpel Sentient"] = {
                Description = "Augmente les dégâts des tourelles contre les ennemis Sentient.",
                Image = "Scalpel Sentient.png",
                Manufacturer = "Vidar",
                Name = "Scalpel Sentient",
                NameEN = "Sentient Scalpel",
                Rarity = "Rare",
                Target = "Tourelles",
                Type = "Integrated",
            },
            ["Soute Étendue"] = {
                Description = "Augmente les réserves maximum de ressources de la forge.",
                Image = "Soute Étendue.png",
                Manufacturer = "Lavan",
                Name = "Soute Étendue",
                NameEN = "Deep Hold",
                Rarity = "Rare",
                Target = "Forge",
                Type = "Integrated",
            },
            ["Structure Renforcée"] = {
                Description = "Réduit la chance de Brèche mineure.",
                Image = "Structure Renforcée.png",
                Manufacturer = "Lavan",
                Name = "Structure Renforcée",
                NameEN = "Hardened Casing",
                Rarity = "Rare",
                Target = "Coque",
                Type = "Integrated",
            },
            ["Surchargeur"] = {
                Description = "Augmente la réserve maximum de munitions pour le Tir Calamité.",
                Image = "Surchargeur.png",
                Manufacturer = "Lavan",
                Name = "Surchargeur",
                NameEN = "Overloader",
                Rarity = "Rare",
                Target = "Tir Calamité",
                Type = "Integrated",
            },
            ["Tempête Ailée"] = {
                Description = "Augmente les dégâts des Archwings à proximité.",
                Image = "Tempête Ailée.png",
                Manufacturer = "Zetki",
                Name = "Tempête Ailée",
                NameEN = "Winged Storm",
                Rarity = "Rare",
                Target = "Archwing",
                Type = "Integrated",
            },
            ["Thermatique"] = {
                Description = "Réduit les dégâts de [[File:Gel_w.png|20px]] Givre.",
                Image = "Thermatique.png",
                Manufacturer = "Lavan",
                Name = "Thermatique",
                NameEN = "Thermatic",
                Rarity = "Commune",
                Target = "Élémentaire",
                Type = "Integrated",
            },
            ["Tissage de Coque"] = {
                Description = "Augmente l'Armure max.",
                Image = "Tissage de Coque.png",
                Manufacturer = "Vidar",
                Name = "Tissage de Coque",
                NameEN = "Hull Weave",
                Rarity = "Inhabituelle",
                Target = "Coque",
                Type = "Integrated",
            },
            ["Tissage de Phase"] = {
                Description = "Réduit les dégâts [[File:Ionique.png|20px]] Ioniques.",
                Image = "Tissage de Phase.png",
                Manufacturer = "Lavan",
                Name = "Tissage de Phase",
                NameEN = "Phasic Weave",
                Rarity = "Commune",
                Target = "Élémentaire",
                Type = "Integrated",
            },
            ["Verrouillage Rapide"] = {
                Description = "Réduit le délai de verrouillage du Tir Calamité.",
                Image = "Verrouillage Rapide.png",
                Manufacturer = "Lavan",
                Name = "Verrouillage Rapide",
                NameEN = "Quicklock",
                Rarity = "Commune",
                Target = "Tir Calamité",
                Type = "Integrated",
            },
            ["Vitesse Calamité"] = {
                Description = "Augmente la vitesse du projectile du Tir Calamité.",
                Image = "Vitesse Calamité.png",
                Manufacturer = "Lavan",
                Name = "Vitesse Calamité",
                NameEN = "Ordnance Velocity",
                Rarity = "Rare",
                Target = "Tir Calamité",
                Type = "Integrated",
            },
            ["Vitesse de Croisière"] = {
                Description = "Augmente la vitesse de base du Railjack lorsqu'il n'y a pas d'ennemis à proximité.",
                Image = "Vitesse de Croisière.png",
                Manufacturer = "Zetki",
                Name = "Vitesse de Croisière",
                NameEN = "Cruising Speed",
                Rarity = "Rare",
                Target = "Moteurs",
                Type = "Integrated",
            },
            ["Vitesse des Tourelles"] = {
                Description = "Augmente la portée des tourelles ainsi que la vitesse de leurs projectiles.",
                Image = "Vitesse_des_Tourelles.png",
                Manufacturer = "Vidar",
                Name = "Vitesse des Tourelles",
                NameEN = "Turret Velocity",
                Rarity = "Rare",
                Target = "Tourelles",
                Type = "Integrated",
            },
    --Stratégique
            ["Brèche Quanta"] = {
                Cooldown = 300,
                Description = "Stabilise temporairement les Brèches de la Coque.",
                Image = "Brèche Quanta.png",
                Name = "Brèche Quanta",
                NameEN = "Breach Quanta",
                Rarity = "Rare",
                Target = "Railjack",
                Type = "Tactical",
            },
            ["Champs de Tir"] = {
                Cooldown = 300,
                Description = "Retire temporairement tous les temps de rechargement des tourelles.",
                Image = "Champs de Tir.png",
                Name = "Champs de Tir",
                NameEN = "Death Blossom",
                Rarity = "Rare",
                Target = "Tourelles",
                Type = "Tactical",
            },
            ["Flux Brûlant"] = {
                Cooldown = 240,
                Description = "Augmente temporairement la vitesse de base et de propulsion.",
                Image = "Flux Brûlant.png",
                Name = "Flux Brûlant",
                NameEN = "Flow Burn",
                Rarity = "Rare",
                Target = "Railjack",
                Type = "Tactical",
            },
            ["Forge de Combat"] = {
                Cooldown = 480,
                Description = "Réduit le temps de rechargement des forges.",
                Image = "Forge de Combat.png",
                Name = "Forge de Combat",
                NameEN = "Battle Forge",
                Rarity = "Rare",
                Target = "Railjack",
                Type = "Tactical",
            },
    
            ["Rassemblement"] = {
                Cooldown = 240,
                Description = "Rappelle tous les membres de l'équipage au Railjack et les soigne.",
                Image = "Rassemblement.png",
                Name = "Rassemblement",
                NameEN = "Form Up",
                Rarity = "Rare",
                Target = "Tenno",
                Type = "Tactical",
            },
            ["Renouvellement d'Escouade"] = {
                Cooldown = 300,
                Description = "Soigne tous les membres de l'équipage du Railjack.",
                Image = "Renouvellement d'Escouade.png",
                Name = "Renouvellement d'Escouade",
                NameEN = "Squad Renew",
                Rarity = "Rare",
                Target = "Tenno",
                Type = "Tactical",
            },
            ["Stase d'Intrus"] = {
                Cooldown = 300,
                Description = "Immobilise temporairement tous les ennemis à bord du Railjack.",
                Image = "Stase d'Intrus.png",
                Name = "Stase d'Intrus",
                NameEN = "Intruder Stasis",
                Rarity = "Rare",
                Target = "Intrus",
                Type = "Tactical",
            },
            ["Stations de Combat"] = {
                Cooldown = 240,
                Description = "Augmentation temporaire des dégâts des tourelles.",
                Image = "Stations de Combat.png",
                Name = "Stations de Combat",
                NameEN = "Battle Stations",
                Rarity = "Rare",
                Target = "Tourelles",
                Type = "Tactical",
            },
            ["Suppression d'Incendie"] = {
                Cooldown = 300,
                Description = "Eteint un certain nombre d'incendies ou de failles électriques.",
                Image = "Suppression d'Incendie.png",
                Name = "Suppression d'Incendie",
                NameEN = "Fire Suppression",
                Rarity = "Rare",
                Target = "Railjack",
                Type = "Tactical",
            },
            ["Voile du Néant"] = {
                Cooldown = 120,
                Description = "Rend le Railjack temporairement invisible au détriment de sa vitesse.",
                Image = "Voile du Néant.png",
                Name = "Voile du Néant",
                NameEN = "Void Cloak",
                Rarity = "Rare",
                Target = "Railjack",
                Type = "Tactical",
            },
    --De Combat
            ["Bélier à Particules"] = {
                Description = "Déploie un bélier à particules infligeant X dégâts/s. Désactiver pour projeter le bélier pendant Xs.",
                Image = "Bélier à Particules.png",
                Name = "Bélier à Particules",
                NameEN  = "Particle Ram",
                Rarity = "Rare",
                Slot = 2,
                Type = "Battle",
            },
            ["Contre-mesures"] = {
                Description = "Déploie X fusées éclairantes détournant les projectiles guidés ennemis.",
                Image = "Contre-mesures.png",
                Name = "Contre-mesures",
                NameEN  = "Countermeasures",
                Rarity = "Rare",
                Slot = 1,
                Type = "Battle",
            },
            ["Explosion Éclatante"] = {
                Description = "Crée un barrage de X explosions/s sur Xs, infligeant X de dégâts dans un rayon de Xm.",
                Image = "Explosion Éclatante.png",
                Name = "Explosion Éclatante",
                NameEN  = "Shatter Burst",
                Rarity = "Rare",
                Slot = 2,
                Type = "Battle",
            },
            ["Grelin"] = {
                Description = "Émet un champ qui restreint les mouvements de X cibles ennemies dans les Xm pendant Xs. Détone en infligeant X dégâts sur Xm.",
                Image = "Grelin.png",
                Name = "Grelin",
                NameEN  = "Tether",
                Rarity = "Rare",
                Slot = 2,
                Type = "Battle",
            },
            ["Phénix Enragé"] = {
                Description = "Laisse une trace de feu infligeant X dégâts par seconde aux ennemis. Obtenez X% en vitesse et X% de réductions aux dégâts lorsqu'actif. Accumule X dégâts/s relâchés sur Xm lorsque désactivé.",
                Image = "Phénix Enragé.png",
                Name = "Phénix Enragé",
                NameEN  = "Fiery Phoenix",
                Rarity = "Rare",
                Slot = 3,
                Type = "Battle",
            },
            ["Impulsion Atonique"] = {
                Description = "Déploie une impulsion électromagnétique, infligeant X de dégâts aux ennemis à moins de 100m de distance, les incapacitant temporairement. Détoner manuellement permet d'agrandir le rayon de l'explosion à Xm.",
                Image = "Impulsion Atonique.png",
                Name = "Impulsion Atonique",
                NameEN  = "Blackout Pulse",
                Rarity = "Rare",
                Slot = 1,
                Type = "Battle",
            },
            ["Salve de Missiles"] = {
                Description = "Tire X missiles à tête chercheuse.",
                Image = "Salve de Missiles.png",
                Name = "Salve de Missiles",
                NameEN  = "Seeker Volley",
                Rarity = "Rare",
                Slot = 3,
                Type = "Battle",
            },
            ["Trou du Néant"] = {
                Description = "Crée un trou noir de Xm aspirant les ennemis et leur infligeant X dégâts/s pendant Xs.",
                Image = "Trou du Néant.png",
                Name = "Trou du Néant",
                NameEN  = "Void Hole",
                Rarity = "Rare",
                Slot = 3,
                Type = "Battle",
            },
            ["Vortex de Munitions"] = {
                Description = "Déploie une bulle absorbant les tirs ennemis pendant Xs. Détone tous les dégâts accumulés sur une distance de Xm.",
                Image = "Vortex de Munitions.png",
                Name = "Vortex de Munitions",
                NameEN  = "Munitions Vortex",
                Rarity = "Rare",
                Slot = 1,
                Type = "Battle",
            },
    }
    
    return AvionicData
    