local EnemyData = {
    -- A
    ["Alad V"] = {
        Affinity = 1713.75,
        BaseLevel = 1,
        Capacities = {},
        Faction = "Corpus",
        Family = "Alad V",
        HealthTypes = {
            ["Armure en Ferrite"] = 250,
            ["Chair"] = 900,
            ["Proto-Bouclier"] = 1500
        },
        Image = "AladV.png",
        Icon = "AladV sigil.png",
        Introduced = "11.0",
        Link = nil,
        Name = "Alad V",
        NameEN = "Alad V",
        Regions = {"Jupiter"},
        Scans = 3,
        SpawnLevel = 20,
        Weapons = {}
    },
    ["Alad V Mutaliste"] = {
        Affinity = 3998.75,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Infesté",
        Family = "Alad V Mutaliste",
        HealthTypes = {
            ["Armure en Ferrite"] = 500,
            ["Infesté"] = 2500,
            ["Proto-Bouclier"] = 1200
        },
        Image = "Alad_Muta.png",
        Icon = "AladV sigil.png",
        Introduced = "15.5",
        Link = nil,
        Name = "Alad V Mutaliste",
        NameEN = "Mutalist Alad V",
        Regions = {"Eris"},
        Scans = 3,
        Weapons = {"Paracyst"}
    },
    ["Ambulas"] = {
        Affinity = 1.500,
        BaseLevel = 1,
        Capacities = {},
        Faction = "Corpus",
        Family = "Ambulas",
        HealthTypes = {
            ["Robot"] = 1.100,
            ["Bouclier"] = 500,
            ["Armure en Alliage"] = 150
        },
        Image = "Ambulas3.png",
        Icon = "Ambulas sigil.png",
        Introduced = "6.0",
        Link = nil,
        Name = "Ambulas",
        NameEN = "Ambulas",
        Regions = {"Pluton"},
        Scans = 3,
        SpawnLevel = 45,
        Weapons = {}
    },
    ["Ancien Guérisseur"] = {
        Affinity = 150,
        BaseLevel = 1,
        Capacities = {},
        Faction = "Infesté",
        Family = "Ancien Guérisseur",
        HealthTypes = {["Fossilisé"] = 400},
        Image = "Ancien_guerisseur.png",
        Icon = nil,
        Introduced = nil,
        Link = nil,
        Name = "Ancien Guérisseur",
        NameEN = "Ancient Healer",
        Regions = {
            "Mercure", "Vénus", "Terre", "Mars", "Jupiter", "Saturne",
            "Uranus", "Neptune", "Pluton", "Cérès", "Éris", "Sedna",
            "Europe", "Phobos", "Deimos"
        },
        Scans = 5,
        SpawnLevel = nil,
        Weapons = {}
    },
    ["Ancien Guérisseur Deimos"] = {
        Affinity = nil,
        BaseLevel = 1,
        Capacities = {},
        Faction = "Infesté",
        Family = "Ancien Guérisseur",
        HealthTypes = {["Fossilisé"] = 400},
        Image = "HealingAncientMicroPlanetAvatar.png",
        Icon = nil,
        Introduced = "29.0",
        Link = nil,
        Name = "Ancien Guérisseur Deimos",
        NameEN = "Deimos Ancient Healer",
        Regions = {"Deimos"},
        Scans = 5,
        SpawnLevel = nil,
        Weapons = {}
    },
    ["Artilleuse Lourde"] = {
        Affinity = 500,
        BaseLevel = 8,
        Capacities = {"Onde de Choc"},
        Faction = "Grineer",
        Family = "Artilleuse Lourde",
        HealthTypes = {["Chair Clonée"] = 300, ["Armure en Ferrite"] = 500},
        Image = "Mitrailleur_Lourd.png",
        Icon = nil,
        Introduced = "Vanilla",
        Link = nil,
        Name = "Artilleuse Lourde",
        NameEN = "Heavy Gunner",
        Regions = {
            "Mercure", "Mars", "Saturne", "Uranus", "Cérès", "Sedna",
            "Deimos", "Lua"
        },
        Scans = 3,
        Weapons = {"Gorgon", "Sheev"}
    },
    ["Artilleuse Lourde Aride"] = {
        Affinity = 500,
        BaseLevel = 8,
        Capacities = {"Onde de Choc"},
        Faction = "Grineer",
        Family = "Artilleuse Lourde",
        HealthTypes = {["Chair Clonée"] = 300, ["Armure en Ferrite"] = 500},
        Image = "DesertHeavyFemaleGrineerAvatarDesert.png",
        Icon = nil,
        Introduced = nil,
        Link = nil,
        Name = "Artilleuse Lourde Aride",
        NameEN = "Arid Heavy Gunner",
        Regions = {"Mars", "Deimos"},
        Scans = 3,
        SpawnLevel = nil,
        Weapons = {"Gorgon", "Sheev"}
    },
    -- B
    ["Baptiste Fanatique"] = {
        Affinity = nil,
        BaseLevel = 1,
        Capacities = {},
        Faction = "Infesté",
        Family = "Fanatique",
        HealthTypes = {["Tendon Infesté"] = 100, ["Chair Infestée"] = 1200},
        Image = "Baptiseur_fanatique.png",
        Icon = nil,
        Introduced = "25.7.3.1",
        Link = nil,
        Name = "Baptiste Fanatique",
        NameEN = "Zealot Baptizer",
        Regions = {},
        Scans = 5,
        Weapons = {}
    },
    -- C
    ["Comba"] = {
        Affinity = 500,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Corpus",
        HealthTypes = {["Bouclier"] = 400, ["Chair"] = 1100},
        Image = "FogBrouillard.png",
        Introduced = "17.5",
        Link = nil,
        Name = "Comba",
        NameEN = "Comba",
        Regions = {"Jupiter", "Neptune", "Pluton", "Europe"},
        Scans = 3,
        Weapons = {"Lecta", "Detron Essaim", "Angstrum Chercheur"}
    },
    -- D
    ["Dargyn"] = {
        Affinity = 57.13,
        BaseLevel = 1,
        Capacities = {},
        Faction = "Grineer",
        HealthTypes = {["Armure en Ferrite"] = 200, ["Chair Clonée"] = 200},
        Image = "GrnSkiff.png",
        Icon = nil,
        Introduced = nil,
        Link = nil,
        Name = "Dargyn",
        NameEN = "Dargyn",
        Regions = {"Espace Libre"},
        Scans = 5,
        Weapons = {}
    },
    ["Dreg Temporel"] = {
        Affinity = 57.13,
        BaseLevel = 1,
        Capacities = {},
        Faction = "Grineer",
        Family = "Dreg",
        HealthTypes = {["Armure en Ferrite"] = 150, ["Chair Clonée"] = 100},
        Image = "GrnStasisDrone.png",
        Icon = nil,
        Introduced = nil,
        Link = nil,
        Name = "Dreg Temporel",
        NameEN = "Temporal Dreg",
        Regions = {"Terre", "Saturne", "Uranus"},
        Scans = 10,
        Weapons = {}
    },
    ["Drone d'Attaque (Archwing)"] = {
        Affinity = 57.13,
        BaseLevel = 1,
        Capacities = {},
        Faction = "Corpus",
        HealthTypes = {["Robot"] = 250, ["Bouclier"] = 75},
        Image = "FusionDroneDE.png",
        Icon = nil,
        Introduced = nil,
        Link = nil,
        Name = "Drone d'Attaque (Archwing)",
        NameEN = "Attack Drone (Archwing Enemy)",
        Regions = {"Vénus", "Mars", "Jupiter", "Neptune"},
        Scans = 20,
        Weapons = {}
    },
    -- E
    -- F
    -- G
    ["Gardien Grineer"] = {
        Affinity = 500,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Grineer",
        HealthTypes = {["Armure en Ferrite"] = 500, ["Chair Clonée"] = 600},
        Image = "DEGrineerWarden.png",
        Icon = nil,
        Introduced = "13.2",
        Link = nil,
        Name = "Gardien Grineer",
        NameEN = "Grineer Warden",
        Regions = {"Cérès"},
        Scans = 3,
        SpawnLevel = nil,
        Weapons = {"Gorgon", "Hind", "Vulkar", "Sheev"}
    },
    ["Général Sargas Ruk"] = {
        Affinity = nil,
        BaseLevel = 1,
        Capacities = {"Grenade Explosive", "Explosion de Feu", "Fournaise"},
        Faction = "Grineer",
        HealthTypes = {["Armure en Alliage"] = 250, ["Chair Clonée"] = 2000},
        Image = "GeneralSargasRukCodex.png",
        Icon = "SargusRuk sigil.png",
        Introduced = "11.0",
        Link = nil,
        Name = "Général Sargas Ruk",
        NameEN = "General Sargas Ruk",
        Regions = {"Saturne"},
        Scans = 3,
        SpawnLevel = 26,
        Weapons = {"Bras Canon"}
    },
    ["Golem Jordas"] = {
        Affinity = nil,
        BaseLevel = 1,
        Capacities = {
            "Canon Laser", "Sphère Électrique", "Vague de Feu",
            "Lanceur de Larves"
        },
        Faction = "Infesté",
        HealthTypes = {["Armure en Ferrite"] = 250, ["Fossilisé"] = 20000},
        Image = "J3Golem.png",
        Icon = nil,
        Introduced = nil,
        Link = nil,
        Name = "Golem Jordas",
        NameEN = "Jordas Golem",
        Regions = {"Eris"},
        Scans = 3,
        SpawnLevel = 34,
        Weapons = nil
    },
    -- H
    ["Hellion"] = {
        Affinity = 250,
        BaseLevel = 1,
        Capacities = {"Jet-Pack", "Barrage de Missiles"},
        Faction = "Grineer",
        Family = "Hellion",
        HealthTypes = {["Armure en Ferrite"] = 100, ["Chair Clonée"] = 100},
        Image = "Hellion.png",
        Icon = nil,
        Introduced = nil,
        Link = nil,
        Name = "Hellion",
        NameEN = "Hellion",
        Regions = {"Cérès", "Sedna", "Deimos"},
        Scans = 5,
        Weapons = {"Grakata", "Sheev"}
    },
    ["Hellion Aride"] = {
        Affinity = 250,
        BaseLevel = 1,
        Capacities = {"Jet-Pack", "Barrage de Missiles"},
        Faction = "Grineer",
        Family = "Hellion",
        HealthTypes = {["Armure en Ferrite"] = 100, ["Chair Clonée"] = 180},
        Image = "HellionAride.png",
        Icon = nil,
        Introduced = nil,
        Link = nil,
        Name = "Hellion Aride",
        NameEN = "Arid Hellion",
        Regions = {"Colonie Grineer"},
        Scans = 5,
        Weapons = {"Grakata", "Sheev"}
    },
    ["Homme d'Équipage"] = {
        Affinity = 57.13,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Corpus",
        Family = "Homme d'Équipage",
        HealthTypes = {["Chair"] = 60, ["Bouclier"] = 150},
        Image = "CrewmanNormal.png",
        Icon = nil,
        Introduced = nil,
        Link = nil,
        Name = "Homme d'Équipage",
        NameEN = "Crewman",
        Regions = {"Vénus", "Mars", "Jupiter", "Phobos", "Europe"},
        Scans = 20,
        Weapons = {"Dera", "Prova"}
    },
    ["Homme d'Équipage Prod"] = {
        Affinity = 50,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Corpus",
        Family = "Homme d'Équipage Prod",
        HealthTypes = {["Bouclier"] = 50, ["Chair"] = 100},
        Image = "250px-CrewmanProd.png",
        Icon = nil,
        Introduced = nil,
        Link = nil,
        Name = "Homme d'Équipage Prod",
        NameEN = "Prod Crewman",
        Regions = {"Vénus", "Mars", "Deimos"},
        Scans = 20,
        Weapons = {"Prova"}
    },
    -- I
    -- J
    ["Jackal"] = {
        Affinity = 1713.75,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Corpus",
        Family = "Jackal",
        HealthTypes = {
            ["Armure en Alliage"] = 100,
            ["Proto-Bouclier"] = 2000,
            ["Robot"] = 1500
        },
        Image = "Jackal_2020.png",
        Icon = "Jackal sigil.png",
        Introduced = "Vanilla",
        Link = nil,
        Name = "Jackal",
        NameEN = "Jackal",
        Regions = {"Vénus"},
        Scans = 3,
        Weapons = {"Mitrailleuses Lourdes"}
    },
    -- K
    -- L
    ["Lancier"] = {
        Affinity = 50,
        BaseLevel = 1,
        Capacities = {"Grenade à Plasma"},
        Faction = "Grineer",
        Family = "Lancier",
        HealthTypes = {["Armure en Ferrite"] = 100, ["Chair Clonée"] = 100},
        Image = "Lancier.png",
        Icon = nil,
        Introduced = nil,
        Link = nil,
        Name = "Lancier",
        NameEN = "Lancer",
        Regions = {"Mercure", "Terre", "Mars", "Cérès", "Deimos"},
        Scans = 20,
        Weapons = {"Grakata", "Sheev"}
    },
    ["Lancier Aride"] = {
        Affinity = 50,
        BaseLevel = 1,
        Capacities = {"Grenade à Plasma"},
        Faction = "Grineer",
        Family = "Lancier",
        HealthTypes = {["Armure en Ferrite"] = 100, ["Chair Clonée"] = 100},
        Image = "DesertRifleLancerAvatar.png",
        Icon = nil,
        Introduced = nil,
        Link = nil,
        Name = "Lancier Aride",
        NameEN = "Arid Lancer",
        Regions = {"Mars", "Deimos"},
        Scans = 20,
        Weapons = {"Grakata", "Sheev"}
    },
    ["Lancier Drekar"] = {
        Affinity = 50,
        BaseLevel = 1,
        Capacities = {"Grenade à Plasma"},
        Faction = "Grineer",
        Family = "Lancier",
        HealthTypes = {["Armure en Ferrite"] = 100, ["Chair Clonée"] = 100},
        Image = "LancierDrekar.png",
        Icon = nil,
        Introduced = "17.0",
        Link = nil,
        Name = "Lancier Drekar",
        NameEN = "Drekar Lancer",
        Regions = {"Terre", "Uranus"},
        Scans = 20,
        Weapons = {"Grakata", "Sheev"}
    },
    ["Lancier d'Élite"] = {
        Affinity = 150,
        BaseLevel = 15,
        Capacities = {"Grenade à Plasma"},
        Faction = "Grineer",
        Family = "Lancier d'Élite",
        HealthTypes = {["Armure en Alliage"] = 200, ["Chair Clonée"] = 150},
        Image = "Lancier_Elite.png",
        Icon = nil,
        Introduced = "9.0",
        Link = nil,
        Name = "Lancier d'Élite",
        NameEN = "Elite Lancer",
        Regions = {"Mercure", "Saturne", "Cérès", "Sedna", "Deimos", "Lua"},
        Scans = 5,
        Weapons = {"Hind", "Sheev"}
    },
    ["Lancier Frontalier"] = {
        Affinity = 50,
        BaseLevel = 1,
        Capacities = {"Grenade à Plasma"},
        Faction = "Grineer",
        Family = "Lancier",
        HealthTypes = {["Armure en Ferrite"] = 100, ["Chair Clonée"] = 100},
        Image = "ForestLancer.png",
        Icon = nil,
        Introduced = nil,
        Link = nil,
        Name = "Lancier Frontalier",
        NameEN = "Frontier Lancer",
        Regions = {"Terre"},
        Scans = 20,
        Weapons = {"Grakata", "Sheev"}
    },
    ["Lancier Ivoire"] = {
        Affinity = 50,
        BaseLevel = 1,
        Capacities = {"Grenade à Plasma"},
        Faction = "Grineer",
        Family = "Lancier",
        HealthTypes = {["Armure en Ferrite"] = 100, ["Chair Clonée"] = 100},
        Image = "EidolonRifleLancer.png",
        Icon = nil,
        Introduced = "22.0",
        Link = nil,
        Name = "Lancier Ivoire",
        NameEN = "Tusk Lancer",
        Regions = {"Terre"},
        Scans = 20,
        Weapons = {"Hind", "Sheev"}
    },
    ["Lancier Kuva"] = {
        Affinity = 50,
        BaseLevel = 1,
        Capacities = {"Grenade à Plasma"},
        Faction = "Grineer",
        Family = "Lancier",
        HealthTypes = {["Armure en Ferrite"] = 100, ["Chair Clonée"] = 100},
        Image = "KuvaLancer.png",
        Icon = nil,
        Introduced = "19.0",
        Link = nil,
        Name = "Lancier Kuva",
        NameEN = "Kuva Lancer",
        Regions = {"Forteresse Kuva"},
        Scans = 20,
        Weapons = {"Kohm", "Sheev"}
    },
    ["Lancier Nightwatch"] = {
        Affinity = 50,
        BaseLevel = 1,
        Capacities = {"Grenade à Plasma"},
        Faction = "Grineer",
        Family = "Lancier",
        HealthTypes = {["Armure en Ferrite"] = 100, ["Chair Clonée"] = 100},
        Image = "Lancier Nightwatch.png",
        Icon = nil,
        Introduced = nil,
        Link = nil,
        Name = "Lancier Nightwatch",
        NameEN = "Nightwatch Lancer",
        Regions = {"Alerte Tactique"},
        Scans = 20,
        Weapons = {"Grinlok", "Sheev"}
    },
    ["Lieutenant Lech Kril"] = {
        Affinity = nil,
        BaseLevel = 1,
        Capacities = {"Vague de Glace", "Vague de Feu", "Barrière de Flammes"},
        Faction = "Grineer",
        Family = "Lieutenant Lech Kril",
        HealthTypes = {
            ["Armure en Alliage"] = 250,
            ["Bouclier"] = 400,
            ["Chair Clonée"] = 4000
        },
        Image = "LechKril.png",
        Icon = "LechKril_sigil.png",
        Introduced = nil,
        Link = nil,
        Name = "Lieutenant Lech Kril",
        NameEN = "Lieutenant Lech Kril",
        Regions = {"Mars"},
        Scans = 3,
        SpawnLevel = 13,
        Weapons = {"Gorgon", "Brokk"}
    },
    -- M
    ["Massacreur Kosma"] = {
        Affinity = nil,
        BaseLevel = 1,
        Capacities = {},
        Faction = "Grineer",
        Family = "Massacreur",
        HealthTypes = {["Chair Clonée"] = 750, ["Armure en Ferrite"] = 200},
        Image = "Massacreur Kosma.png",
        Icon = nil,
        Introduced = 27.0,
        Link = nil,
        Name = "Massacreur Kosma",
        NameEN = "Kosma Butcher",
        Regions = {"Proxima de la Terre"},
        Scans = 20,
        Weapons = {"Machette"}
    },
    ["Messager Fanatique"] = {
        Affinity = nil,
        BaseLevel = 1,
        Capacities = {},
        Faction = "Infesté",
        Family = "Fanatique",
        HealthTypes = {["Tendon Infesté"] = 200, ["Chair Infestée"] = 1000},
        Image = "MessagerFanatique.png",
        Icon = nil,
        Introduced = "25.3",
        Link = nil,
        Name = "Messager Fanatique",
        NameEN = "Zealot Proselytizer",
        Regions = {},
        Scans = 5,
        Weapons = {"Torid"}
    },
    ["MOA à Canon Électrique"] = {
        Affinity = 114.25,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Corpus",
        Family = "MOA à Canon Électrique",
        HealthTypes = {["Bouclier"] = 150, ["Robot"] = 60},
        Image = "MoaRailgun.png",
        Icon = nil,
        Introduced = nil,
        Link = nil,
        Name = "MOA à Canon Électrique",
        NameEN = "Railgun MOA",
        Regions = {
            "Vénus", "Mars", "Neptune", "Pluton", "Europe", "Le Néant", "Lua"
        },
        Scans = 10,
        Weapons = {"Canon Électrique"}
    },
    ["MOA Mutaliste Essaim"] = {
        Affinity = 150,
        BaseLevel = 12,
        Capacities = {"Onde de Choc"},
        Faction = "Infesté",
        Family = "MOA Mutaliste Essaim",
        HealthTypes = {["Fossilisé"] = 350},
        Image = "MOA-Essaim.png",
        Icon = nil,
        Introduced = nil,
        Link = nil,
        Name = "MOA Mutaliste Essaim",
        NameEN = "Swarm Mutalist MOA",
        Regions = {
            "Mercure", "Vénus", "Terre", "Mars", "Jupiter", "Saturne",
            "Uranus", "Neptune", "Pluton", "Cérès", "Éris", "Sedna",
            "Europe", "Phobos", "Deimos"
        },
        Scans = 5,
        Weapons = {"Spores Infestées"}
    },
    -- N
    -- O
    ["Officier Gokstad"] = {
        Affinity = nil,
        BaseLevel = 8,
        Capacities = nil,
        Faction = "Grineer",
        Family = "Officier Gokstad",
        HealthTypes = {["Chair Clonée"] = 1000, ["Armure en Ferrite"] = 1000},
        Image = "KosmaGokstadOfficer.png",
        Icon = nil,
        Introduced = "27.0",
        Link = nil,
        Name = "Officier Gokstad",
        NameEN = "Gokstad Officer",
        Regions = nil,
        Scans = 3,
        SpawnLevel = nil,
        Weapons = {"Karak Wraith"}
    },
    -- P
    ["Prosélyte Fanatique"] = {
        Affinity = nil,
        BaseLevel = 1,
        Capacities = {},
        Faction = "Infesté",
        Family = "Fanatique",
        HealthTypes = {["Tendon Infesté"] = 200, ["Chair Infestée"] = 1200},
        Image = "Prosélyte_Fanatique.png",
        Icon = nil,
        Introduced = "25.3",
        Link = nil,
        Name = "Prosélyte Fanatique",
        NameEN = "Zealot Proselytizer",
        Regions = {},
        Scans = 5,
        Weapons = {"Zymos"}
    },
    -- Q
    -- R
    ["Ropalolyste"] = {
        Affinity = nil,
        BaseLevel = 17,
        Capacities = {
            "Lasers", "Hurlement Zéro", "Flux Électrique", "Laser Géant",
            "Missiles à Têtes Chercheuses", "Attrape"
        },
        Faction = "Sentient",
        Family = "Ropalolyste",
        HealthTypes = {
            ["Armure en Alliage"] = 200,
            ["Bouclier"] = 2000,
            ["Robot"] = 5000
        },
        Image = "Ropalolyst.png",
        Icon = nil,
        Introduced = "25.0",
        Link = nil,
        Name = "Ropalolyste",
        NameEN = "Ropalolyste",
        Regions = {"Jupiter"},
        Scans = 3,
        Weapons = {}
    },
    -- S
    ["Scorpion"] = {
        Affinity = 145.06,
        BaseLevel = 10,
        Capacities = {"Ligne d'Arrachage"},
        Faction = "Grineer",
        Family = "Scorpion",
        HealthTypes = {["Armure en Ferrite"] = 150, ["Chair Clonée"] = 150},
        Image = "250px-ScorpionDE.png",
        Icon = nil,
        Introduced = "8.0",
        Link = nil,
        Name = "Scorpion",
        NameEN = "Scorpion",
        Regions = {
            "Mercure", "Terre", "Mars", "Saturne", "Cérès", "Sedna",
            "Le Néant", "Deimos", "Lua"
        },
        Scans = 10,
        Weapons = {"Machette"}
    },
    ["Stalker"] = {
        Affinity = 1713.75,
        BaseLevel = 1,
        Capacities = {
            "Élan Tranchant", "Téléportation", "Absorption", "Attraction",
            "Écran de Fumée", "Jugement"
        },
        Faction = "Stalker",
        Family = "Stalker",
        HealthTypes = {
            ["Armure en Alliage"] = 300,
            ["Chair"] = 450,
            ["Proto-Bouclier"] = 200
        },
        Image = "Stalker_cdx.png",
        Icon = "StalkerSigil.png",
        Introduced = "7.0",
        Link = nil,
        Name = "Stalker",
        NameEN = "Stalker",
        Regions = {"Toutes"},
        Scans = 3,
        Weapons = {"Dread", "Despair", "Hate"}
    },
    -- T
    -- U
    -- V
    -- W
    -- X
    -- Y
    -- Z
    ["Zeplen"] = {
        Affinity = 2000,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Grineer",
        Family = nil,
        HealthTypes = {["Armure en Ferrite"] = 2750, ["Chair Clonée"] = 400},
        Image = "GrnMissilePlatform.png",
        Icon = nil,
        Introduced = nil,
        Link = nil,
        Name = "Zeplen",
        NameEN = "Zeplen",
        Regions = nil,
        Scans = 3,
        Weapons = nil
    }
}

return EnemyData
