local EnemyData = {
    -- A
    ["Alad V"] = {
        Affinity = 1713.75,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Corpus",
        Family = "Alad V",
        HealthTypes = {
            ["Armure en Ferrite"] = 250,
            ["Chair"] = 900,
            ["Proto-Bouclier"] = 1500
        },
        Image = "AladV.png",
        Icon = "AladV sigil.png",
        Introduced = "11.0",
        Link = nil,
        Name = "Alad V",
        NameEN = "Alad V",
        Regions = {"Jupiter"},
        Scans = 3,
        SpawnLevel = 20,
        Weapons = nil
    },
    ["Alad V Mutaliste"] = {
        Affinity = 3998.75,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Infesté",
        Family = "Alad V Mutaliste",
        HealthTypes = {
            ["Armure en Ferrite"] = 500,
            ["Infesté"] = 2500,
            ["Proto-Bouclier"] = 1200
        },
        Image = "Alad_Muta.png",
        Icon = "AladV sigil.png",
        Introduced = "15.5",
        Link = nil,
        Name = "Alad V Mutaliste",
        NameEN = "Mutalist Alad V",
        Regions = {"Eris"},
        Scans = 3,
        Weapons = {"Paracyst"}
    },
    ["Ambulas"] = {
        Affinity = 1.500,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Corpus",
        Family = "Ambulas",
        HealthTypes = {
            ["Robot"] = 1.100,
            ["Bouclier"] = 500,
            ["Armure en Alliage"] = 150
        },
        Icon = "Ambulas sigil.png",
        Image = "Ambulas3.png",
        Introduced = "6.0",
        Link = nil,
        Name = "Ambulas",
        NameEN = "Ambulas",
        Regions = {"Pluton"},
        Scans = 3,
        SpawnLevel = 45,
        Weapons = nil
    },
    ["Ambulas Terra"] = {
        Affinity = nil,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Corpus",
        Family = "Ambulas",
        HealthTypes = {
            ["Armure en Ferrite"] = 150,
            ["Bouclier"] = 500,
            ["Robot"] = 1500
        },
        Image = "Ambulas_Terra.png",
        Introduced = "24.2",
        Link = nil,
        Name = "Ambulas Terra",
        NameEN = "Terra Ambulas",
        Regions = {"Vénus"},
        Scans = 3,
        Weapons = nil
    },
    ["Ancien Corrompu"] = {
        Affinity = 150,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Orokin",
        Family = "Ancien Corrompu",
        HealthTypes = {["Fossilisé"] = 400},
        Image = "AncienCorrompu.png",
        Icon = nil,
        Introduced = nil,
        Link = nil,
        Name = "Ancien Corrompu",
        NameEN = "Corrupted Ancient",
        Regions = {"Le Néant"},
        Scans = 5,
        SpawnLevel = nil,
        Weapons = nil
    },
    ["Ancien Guérisseur"] = {
        Affinity = 150,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Infesté",
        Family = "Ancien Guérisseur",
        HealthTypes = {["Fossilisé"] = 400},
        Image = "Ancien_guerisseur.png",
        Icon = nil,
        Introduced = nil,
        Link = nil,
        Name = "Ancien Guérisseur",
        NameEN = "Ancient Healer",
        Regions = {
            "Mercure", "Vénus", "Terre", "Mars", "Jupiter", "Saturne",
            "Uranus", "Neptune", "Pluton", "Cérès", "Éris", "Sedna",
            "Europe", "Phobos", "Deimos"
        },
        Scans = 5,
        SpawnLevel = nil,
        Weapons = nil
    },
    ["Ancien Guérisseur Deimos"] = {
        Affinity = nil,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Infesté",
        Family = "Ancien Guérisseur",
        HealthTypes = {["Fossilisé"] = 400},
        Image = "HealingAncientMicroPlanetAvatar.png",
        Icon = nil,
        Introduced = "29.0",
        Link = nil,
        Name = "Ancien Guérisseur Deimos",
        NameEN = "Deimos Ancient Healer",
        Regions = {"Deimos"},
        Scans = 5,
        SpawnLevel = nil,
        Weapons = nil
    },
    ["Aquila Vapos"] = {
        Affinity = nil,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Corpus",
        Family = "Aquila",
        HealthTypes = {["Armure en Alliage"] = 500, ["Robot"] = 1000},
        Image = "VaposAquila.png",
        Icon = nil,
        Introduced = "25.0",
        Link = nil,
        Name = "Aquila Vapos",
        NameEN = "Vapos Aquila",
        Regions = {"Jupiter"},
        Scans = 5,
        SpawnLevel = nil,
        Weapons = {"Tourelle Laser"}
    },
    ["Artilleuse Lourde"] = {
        Affinity = 500,
        BaseLevel = 8,
        Capacities = {"Onde de Choc"},
        Faction = "Grineer",
        Family = "Artilleuse Lourde",
        HealthTypes = {["Chair Clonée"] = 300, ["Armure en Ferrite"] = 500},
        Image = "Mitrailleur_Lourd.png",
        Icon = nil,
        Introduced = "Vanilla",
        Link = nil,
        Name = "Artilleuse Lourde",
        NameEN = "Heavy Gunner",
        Regions = {
            "Mercure", "Mars", "Saturne", "Uranus", "Cérès", "Sedna",
            "Deimos", "Lua"
        },
        Scans = 3,
        Weapons = {"Gorgon", "Sheev"}
    },
    ["Artilleuse Lourde Aride"] = {
        Affinity = 500,
        BaseLevel = 8,
        Capacities = {"Onde de Choc"},
        Faction = "Grineer",
        Family = "Artilleuse Lourde",
        HealthTypes = {["Chair Clonée"] = 300, ["Armure en Ferrite"] = 500},
        Image = "DesertHeavyFemaleGrineerAvatarDesert.png",
        Icon = nil,
        Introduced = nil,
        Link = nil,
        Name = "Artilleuse Lourde Aride",
        NameEN = "Arid Heavy Gunner",
        Regions = {"Mars", "Deimos"},
        Scans = 3,
        SpawnLevel = nil,
        Weapons = {"Gorgon", "Sheev"}
    },
    ["Artilleuse Lourde Ivoire"] = {
        Affinity = 500,
        BaseLevel = 8,
        Capacities = {"Onde de Choc"},
        Faction = "Grineer",
        Family = "Artilleuse Lourde",
        HealthTypes = {["Armure en Ferrite"] = 500, ["Chair Clonée"] = 300},
        Image = "EidolonMinigunBombard.png",
        Introduced = nil,
        Link = nil,
        Name = "Artilleuse Lourde Ivoire",
        NameEN = "Tusk Heavy Gunner",
        Regions = {"Terre"},
        Scans = 3,
        SpawnLevel = nil,
        Weapons = {"Grattler Ivoire", "Kohmak", "Sheev"}
    },
    ["Artilleuse Lourde Kuva"] = {
        Affinity = 500,
        BaseLevel = 8,
        Capacities = {"Onde de Choc"},
        Faction = "Grineer",
        Family = "Artilleuse Lourde",
        HealthTypes = {["Armure en Ferrite"] = 500, ["Chair Clonée"] = 300},
        Image = "KuvaHeavyGunner.png",
        Introduced = nil,
        Link = nil,
        Name = "Artilleuse Lourde Kuva",
        NameEN = "Kuva Heavy Gunner",
        Regions = {"Forteresse Kuva"},
        Scans = 3,
        SpawnLevel = nil,
        Weapons = {"Drakgoon", "Sheev"}
    },
    -- B
    ["Baptiste Fanatique"] = {
        Affinity = nil,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Infesté",
        Family = "Fanatique",
        HealthTypes = {["Tendon Infesté"] = 100, ["Chair Infestée"] = 1200},
        Image = "Baptiseur_fanatique.png",
        Icon = nil,
        Introduced = "25.7.3.1",
        Link = nil,
        Name = "Baptiste Fanatique",
        NameEN = "Zealot Baptizer",
        Regions = nil,
        Scans = 5,
        Weapons = nil
    },
    ["Bombardier"] = {
        Affinity = 500,
        BaseLevel = 4,
        Capacities = {"Onde de Choc"},
        Faction = "Grineer",
        Family = "Bombardier",
        HealthTypes = {["Armure en Alliage"] = 500, ["Chair Clonée"] = 300},
        Image = "250px-Bombardier.png",
        Introduced = nil,
        Link = nil,
        Name = "Bombardier",
        NameEN = "Bombard",
        Regions = {
            "Mercure", "Terre", "Mars", "Saturne", "Uranus", "Cérès", "Sedna",
            "Lua"
        },
        Scans = 3,
        Weapons = {"Ogris", "Sheev"}
    },
    ["Bombardier Ivoire"] = {
        Affinity = 500,
        BaseLevel = 1,
        Capacities = {"Onde de Choc"},
        Faction = "Grineer",
        Family = "Bombardier",
        HealthTypes = {["Armure en Alliage"] = 500, ["Chair Clonée"] = 300},
        Image = "Tusk Bombard.png",
        Introduced = nil,
        Link = nil,
        Name = "Bombardier Ivoire",
        NameEN = "Tusk Bombard",
        Regions = {"Terre"},
        Scans = 3,
        Weapons = {"Ogris", "Sheev"}
    },
    ["Bombardier Kuva"] = {
        Affinity = 500,
        BaseLevel = 4,
        Capacities = nil,
        Faction = "Grineer",
        Family = "Bombardier",
        HealthTypes = {["Armure en Alliage"] = 500, ["Chair Clonée"] = 300},
        Image = "KuvaBombard.png",
        Icon = nil,
        Introduced = "19.0",
        Link = nil,
        Name = "Bombardier Kuva",
        NameEN = "Kuva Bombard",
        Regions = {"Forteresse Kuva"},
        Scans = 3,
        Weapons = {"Ogris", "Sheev"}
    },
    ["Bombardier Maniaque"] = {
        Affinity = nil,
        BaseLevel = 4,
        Capacities = {"Téléportation"},
        Faction = "Grineer",
        Family = "Bombardier Maniaque",
        HealthTypes = {["Armure en Alliage"] = 500, ["Chair Clonée"] = 1500},
        Image = "BombardierManiaque.png",
        Introduced = "17.0",
        Link = nil,
        Name = "Bombardier Maniaque",
        NameEN = "Manic Bombard",
        Regions = {"Uranus"},
        Scans = 3,
        Weapons = {"Gorgon", "Sheev"}
    },
    ["Bombardier Maniaque Drekar"] = {
        Affinity = nil,
        BaseLevel = 4,
        Capacities = {"Téléportation"},
        Faction = "Grineer",
        Family = "Bombardier Maniaque",
        HealthTypes = {["Armure en Alliage"] = 500, ["Chair Clonée"] = 1750},
        Image = "ManicBombardDrekar.png",
        Introduced = nil,
        Link = nil,
        Name = "Bombardier Maniaque Drekar",
        NameEN = "Drekar Manic Bombard",
        Regions = {"Uranus"},
        Scans = 3,
        Weapons = {"Gorgon", "Sheev"}
    },
    ["Bombardier Mortier Ivoire"] = {
        Affinity = nil,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Grineer",
        Family = "Bombardier Mortier",
        HealthTypes = {["Armure en Alliage"] = 500, ["Chair Clonée"] = 300},
        Image = "Bombardier Mortier Ivoire.png",
        Introduced = nil,
        Link = nil,
        Name = "Bombardier Mortier Ivoire",
        NameEN = "Tusk Mortar Bombard",
        Regions = {"Terre"},
        Scans = 3,
        Weapons = {"Kraken", "Mortier", "Sheev"}
    },
    ["Bourreau Dhurnam"] = {
        Affinity = nil,
        BaseLevel = nil,
        Capacities = nil,
        Faction = "Grineer",
        Family = "Bourreau",
        HealthTypes = {
            ["Chair Clonée"] = 600,
            ["Armure en Alliage"] = 300,
            ["Bouclier"] = 600
        },
        Image = "GrineerHeavy.png",
        Icon = nil,
        Introduced = "Lunaro",
        Link = nil,
        Name = "Bourreau Dhurnam",
        NameEN = "Executioner Dhurnam",
        Regions = {"Sedna"},
        Scans = 5,
        SpawnLevel = nil,
        Weapons = {"Doubles Hek", "Fragor"}
    },
    -- C
    ["Capitaine Pyr"] = {
        Affinity = nil,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Grineer",
        Family = "Capitaine Pyr",
        HealthTypes = {["Armure en Alliage"] = 750, ["Chair Clonée"] = 300},
        Image = "PyrCaptain.png",
        Introduced = "27.0",
        Link = nil,
        Name = "Capitaine Pyr",
        NameEN = "Pyr Captain",
        Regions = {"Proxima de la Terre", "Proxima du Voile"},
        Scans = 3,
        SpawnLevel = 1,
        Weapons = nil
    },
    ["Carabus"] = {
        Affinity = nil,
        BaseLevel = "5",
        Capacities = nil,
        Faction = "Grineer",
        Family = "Carabus",
        HealthTypes = {["Bouclier"] = 150, ["Machines"] = 750},
        Image = "Carabus.png",
        Introduced = nil,
        Link = nil,
        Name = "Carabus",
        NameEN = "Carabus",
        Regions = nil,
        Scans = 5,
        Weapons = {"Atomos"}
    },
    ["Carnis Deimos"] = {
        Affinity = nil,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Infesté",
        Family = "Carnis",
        HealthTypes = {["Chair Fossilisée"] = 600, ["Tendon Infesté"] = 50},
        Image = "Carnis Deimos.png",
        Icon = nil,
        Introduced = "29.0",
        Link = nil,
        Name = "Carnis Deimos",
        NameEN = "Deimos Carnis",
        Regions = {"Deimos"},
        Scans = 30,
        Weapons = nil
    },
    ["Carnis Rex Deimos"] = {
        Affinity = nil,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Infesté",
        Family = "Carnis",
        HealthTypes = {["Chair Fossilisée"] = 1600, ["Tendon Infesté"] = 150},
        Image = "Carnis_Deimos_Rex.webp",
        Icon = nil,
        Introduced = 29.0,
        Link = nil,
        Name = "Carnis Rex Deimos",
        NameEN = "Deimos Carnis Rex",
        Regions = {"Deimos"},
        Scans = 3,
        SpawnLevel = nil,
        Weapons = nil
    },
    ["Chroma Infesté"] = {
        Affinity = nil,
        BaseLevel = 1,
        Capacities = {
            "Hurlement Spectral", "Protection Élémentaire",
            "Armure d'Épines", "Effigie"
        },
        Faction = "Infesté",
        Family = nil,
        HealthTypes = {
            ["Chair"] = 2000,
            ["Armure en Ferrite"] = 200,
            ["Bouclier"] = 1000
        },
        Image = "Chroma_Infesté.png",
        Icon = nil,
        Introduced = nil,
        Link = nil,
        Name = "Chroma Infesté",
        NameEN = "Infested Chroma",
        Regions = {"Phobos", "Europe"},
        Scans = 3,
        SpawnLevel = nil,
        Weapons = {"Dera", "Épée à Plasma"}
    },
    ["Cible Corpus Cestra"] = {
        Affinity = nil,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Corpus",
        Family = "Cible Corpus",
        HealthTypes = {
            ["Armure en Ferrite"] = 50,
            ["Bouclier"] = 1200,
            ["Chair"] = 800
        },
        Image = "CorpusCestraTarget.png",
        Introduced = "24.0",
        Link = nil,
        Name = "Cible Corpus Cestra",
        NameEN = "Corpus Cestra Target",
        Regions = {"Vénus"},
        Scans = 3,
        Weapons = {"{{Wepon|Doubles Cestra}}"}
    },
    ["Cible Corpus Sniper"] = {
        Affinity = nil,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Corpus",
        Family = nil,
        HealthTypes = {
            ["Chair"] = 1000,
            ["Armure en Ferrite"] = 50,
            ["Bouclier"] = 1200
        },
        Image = "Cible_corpus_sniper.png",
        Icon = nil,
        Introduced = 24.0,
        Link = nil,
        Name = "Cible Corpus Sniper",
        NameEN = "Corpus Sniper Target",
        Regions = {"Venus"},
        Scans = 3,
        SpawnLevel = nil,
        Weapons = {"Lanka", "Penta"}
    },
    ["Cible Corpus Supra"] = {
        Affinity = nil,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Corpus",
        Family = nil,
        HealthTypes = {
            ["Chair"] = 800,
            ["Armure en Ferrite"] = 50,
            ["Bouclier"] = 1200
        },
        Image = "Cible_corpus_supra.png",
        Icon = nil,
        Introduced = 24.0,
        Link = nil,
        Name = "Cible Corpus Supra",
        NameEN = "Corpus Supra Target",
        Regions = {"Venus"},
        Scans = 3,
        SpawnLevel = nil,
        Weapons = {"Supra"}
    },
    ["Cible Corpus Trencher"] = {
        Affinity = nil,
        BaseLevel = 15,
        Capacities = nil,
        Faction = "Corpus",
        Family = nil,
        HealthTypes = {
            ["Chair"] = 800,
            ["Armure en Ferrite"] = 50,
            ["Bouclier"] = 1200
        },
        Image = "Cible_corpus_trencher.png",
        Icon = nil,
        Introduced = 24.0,
        Link = nil,
        Name = "Cible Corpus Trencher",
        NameEN = "Corpus Trencher Target",
        Regions = {"Venus"},
        Scans = 3,
        SpawnLevel = nil,
        Weapons = {"Doubles Kreska"}
    },
    ["Comba"] = {
        Affinity = 500,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Corpus",
        HealthTypes = {["Bouclier"] = 400, ["Chair"] = 1100},
        Image = "FogBrouillard.png",
        Introduced = "17.5",
        Link = nil,
        Name = "Comba",
        NameEN = "Comba",
        Regions = {"Jupiter", "Neptune", "Pluton", "Europe"},
        Scans = 3,
        Weapons = {"Lecta", "Detron Essaim", "Angstrum Chercheur"}
    },
    ["Commandant Aérien"] = {
        Affinity = nil,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Grineer",
        Family = nil,
        HealthTypes = {["Chair Clonée"] = 800, ["Armure en Alliage"] = 250},
        Image = "Aerial Commander.png",
        Icon = nil,
        Introduced = "22.0",
        Link = nil,
        Name = "Commandant Aérien",
        NameEN = "Aerial Commander",
        Regions = {"Terre"},
        Scans = 3,
        SpawnLevel = nil,
        Weapons = {"Hind", "Fragor"}
    },
    ["Commandante de Reconnaissance"] = {
        Affinity = nil,
        BaseLevel = 3,
        Capacities = {"Onde de Choc Sismique"},
        Faction = "Grineer",
        HealthTypes = {["Armure en Alliage"] = 250, ["Chair Clonée"] = 1200},
        Icon = nil,
        Image = "EidolonVipSniper.png",
        Introduced = "22.0",
        Link = nil,
        Name = "Commandante de Reconnaissance",
        NameEN = "Recon Commander",
        Regions = {"Terre"},
        Scans = 3,
        Weapons = {"Tonkor", "Scindo"}
    },
    ["Commandant des Plaines"] = {
        Affinity = nil,
        BaseLevel = 3,
        Capacities = nil,
        Faction = "Grineer",
        Family = nil,
        HealthTypes = {["Chair Clonée"] = 1200, ["Armure en Alliage"] = 250},
        Image = "Commandant des Plaines.png",
        Icon = nil,
        Introduced = "22.0",
        Link = nil,
        Name = "Commandant des Plaines",
        NameEN = "Aerial Commander",
        Regions = {"Terre"},
        Scans = 3,
        SpawnLevel = nil,
        Weapons = {"Hind", "Fragor"}
    },
    ["Commandant Lektro"] = {
        Affinity = nil,
        BaseLevel = nil,
        Capacities = nil,
        Faction = "Grineer",
        Family = nil,
        HealthTypes = {["Chair Clonée"] = 300, ["Armure en Alliage"] = 750},
        Image = "Commandant Lektro.png",
        Icon = nil,
        Introduced = "27.0",
        Link = nil,
        Name = "Commandant Lektro",
        NameEN = "Lektro Commander",
        Regions = {"Proxima de Saturne"},
        Scans = 3,
        SpawnLevel = nil,
        Weapons = nil
    },
    ["Conculyste"] = {
        Affinity = 571.25,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Sentient",
        Family = "Conculyste",
        HealthTypes = {["Robotique"] = 1300, ["Armure en Ferrite"] = 250},
        Image = "Conculyste.png",
        Icon = nil,
        Introduced = nil,
        Link = nil,
        Name = "Conculyste",
        NameEN = "Conculyst",
        Regions = {"Lua", "Uranus", "Proxima du Voile"},
        Scans = 5,
        SpawnLevel = nil,
        Weapons = nil
    },
    ["Conseiller Vay Hek"] = {
        Affinity = nil,
        BaseLevel = 1,
        Capacities = nil,
        Family = "Conseiller Vay Hek",
        Faction = "Grineer",
        HealthTypes = {["Armure en Ferrite"] = 225, ["Machines"] = 1800},
        Icon = "VeyHek_sigil.png",
        Image = "VayHekPortrait.png",
        Introduced = nil,
        Link = nil,
        Name = "Conseiller Vay Hek",
        NameEN = "Councilor Vay Hek",
        Regions = {"Terre"},
        Scans = 3,
        Weapons = nil
    },
    ["Conseiller Vay Hek - Armure Terra"] = {
        Affinity = nil,
        BaseLevel = 1,
        Capacities = nil,
        Family = "Conseiller Vay Hek",
        Faction = "Grineer",
        HealthTypes = {["Armure en Ferrite"] = 200, ["Machines"] = 2000},
        Image = "VayHek2.png",
        Introduced = nil,
        Link = "Conseiller Vay Hek",
        Name = "Conseiller Vay Hek - Armure Terra",
        NameEN = "Vay Hek Terra Frame",
        Regions = {"Terre"},
        Scans = 3,
        Weapons = nil
    },
    ["Contre-MOA Terra"] = {
        Affinity = nil,
        BaseLevel = 1,
        Capacities = nil,
        Family = "Contre-MOA",
        Faction = "Corpus",
        HealthTypes = {
            ["Armure en Ferrite"] = 0,
            ["Bouclier"] = 0,
            ["Robot"] = 0
        },
        Image = nil,
        Introduced = "24.0",
        Link = nil,
        Name = "Contre-MOA Terra",
        NameEN = "Terra Anti MOA",
        Regions = {"Vénus"},
        Scans = 5,
        Weapons = nil
    },
    ["Coureur Volatile"] = {
        Affinity = 50,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Infesté",
        Family = "Coureur Volatile",
        HealthTypes = {["Chair Infestée"] = 80},
        Image = "Coureur volatil.png",
        Icon = nil,
        Introduced = nil,
        Link = nil,
        Name = "Coureur Volatile",
        NameEN = "Volatile Runner",
        Regions = {
            "Terre", "Venus", "Mercure", "Mars", "Deimos", "Phobos", "Ceres",
            "Jupiter", "Saturne", "Uranus", "Neptune", "Pluton", "Sedna", "Eris"
        },
        Scans = 20,
        SpawnLevel = nil,
        Weapons = nil
    },
    ["Coutelas Pillard Exo"] = {
        Affinity = 150,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Grineer",
        Family = "Coutelas Pillard",
        HealthTypes = {["Armure en Ferrite"] = 200, ["Chair Clonée"] = 1000},
        Icon = nil,
        Image = "ExoRaiderCarver.png",
        Introduced = "27.0",
        Link = nil,
        Name = "Coutelas Pillard Exo",
        NameEN = "Exo Raider Carver",
        Regions = {"Proxima du Voile"},
        Scans = 5,
        Weapons = nil
    },
    -- D
    ["Dargyn"] = {
        Affinity = 57.13,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Grineer",
        Family = "Dargyn",
        HealthTypes = {["Armure en Ferrite"] = 200, ["Chair Clonée"] = 200},
        Image = "GrnSkiff.png",
        Icon = nil,
        Introduced = nil,
        Link = nil,
        Name = "Dargyn",
        NameEN = "Dargyn",
        Regions = {"Espace Libre"},
        Scans = 5,
        Weapons = nil
    },
    ["Dargyn Bouclier"] = {
        Affinity = 100,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Grineer",
        Family = "Dargyn Bouclier",
        HealthTypes = {["Armure en Ferrite"] = 200, ["Chair Clonée"] = 100},
        Image = "GrnSkiffShield.png",
        Icon = nil,
        Introduced = nil,
        Link = nil,
        Name = "Dargyn Bouclier",
        NameEN = "Shield Dargyn",
        Regions = {"Espace Libre"},
        Scans = 5,
        Weapons = nil
    },
    ["Diploïde Commun"] = {
        Affinity = nil,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Infesté",
        Family = nil,
        HealthTypes = {["Chair Fossilisée"] = 250, ["Tendon Infesté"] = 125},
        Image = "Diploïde Commun.png",
        Icon = nil,
        Introduced = "29.5",
        Link = nil,
        Name = "Diploïde Commun",
        NameEN = "Basal Diploid",
        Regions = {"Deimos"},
        Scans = 5,
        Weapons = nil
    },
    ["Diploïde Rex Commun"] = {
        Affinity = nil,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Infesté",
        Family = nil,
        HealthTypes = {["Chair Fossilisée"] = 750},
        Image = "Diploïde Rex Commun.png",
        Icon = nil,
        Introduced = "29.5",
        Link = nil,
        Name = "Diploïde Rex Commun",
        NameEN = "Basal Diploid Rex",
        Regions = {"Deimos"},
        Scans = 5,
        Weapons = nil
    },
    ["Diploïde Rex Sauvage"] = {
        Affinity = nil,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Infesté",
        Family = nil,
        HealthTypes = {["Chair Fossilisée"] = 750},
        Image = "Diploïde Rex Sauvage.png",
        Icon = nil,
        Introduced = "29.5",
        Link = nil,
        Name = "Diploïde Rex Sauvage",
        NameEN = "Feral Diploid Rex",
        Regions = {"Deimos"},
        Scans = 5,
        Weapons = nil
    },
    ["Diploïde Sauvage"] = {
        Affinity = nil,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Infesté",
        Family = nil,
        HealthTypes = {["Chair Fossilisée"] = 250, ["Tendon Infesté"] = 125},
        Image = "Diploïde Sauvage.png",
        Icon = nil,
        Introduced = "29.5",
        Link = nil,
        Name = "Diploïde Sauvage",
        NameEN = "Feral Diploid",
        Regions = {"Deimos"},
        Scans = 5,
        Weapons = nil
    },
    ["Directeur de Biologie"] = {
        Affinity = nil,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Corpus",
        Family = "Directeur de Biologie",
        HealthTypes = {
            ["Armure en Ferrite"] = 100,
            ["Bouclier"] = 1200,
            ["Chair"] = 1750
        },
        Icon = nil,
        Image = "VivisectDirector.png",
        Introduced = "24.2",
        Link = nil,
        Name = "Directeur de Biologie",
        NameEN = "Vivisect Director",
        Regions = {"Vénus"},
        Scans = 3,
        Weapons = {"Plinx"}
    },
    ["Directeur de l'Armement"] = {
        Affinity = nil,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Corpus",
        Family = "Directeur de l'Armement",
        HealthTypes = {
            ["Armure en Ferrite"] = 100,
            ["Bouclier"] = 1200,
            ["Chair"] = 1750
        },
        Icon = nil,
        Image = "ArmamentsDirector.png",
        Introduced = "24.2",
        Link = nil,
        Name = "Directeur de l'Armement",
        NameEN = "Armaments Director",
        Regions = {"Vénus"},
        Scans = 3,
        Weapons = {"Exergis"}
    },
    ["Directeur de Recherche Sentient"] = {
        Affinity = nil,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Corpus",
        Family = "Directeur de Recherche Sentient",
        HealthTypes = {
            ["Armure en Ferrite"] = 100,
            ["Bouclier"] = 1200,
            ["Chair"] = 1750
        },
        Icon = nil,
        Image = "SentientResearchDirector.png",
        Introduced = "24.2",
        Link = nil,
        Name = "Directeur de Recherche Sentient",
        NameEN = "Sentient Research Director",
        Regions = {"Vénus"},
        Scans = 3,
        Weapons = {"Supra Vandal"}
    },
    ["Drahk"] = {
        Affinity = 50,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Grineer",
        Family = "Drahk",
        HealthTypes = {["Armure en Ferrite"] = 100, ["Chair"] = 200},
        Icon = nil,
        Image = "Drahk.png",
        Introduced = "15.0",
        Link = nil,
        Name = "Drahk",
        NameEN = "Drahk",
        Regions = {"Sedna"},
        Scans = 20,
        Weapons = nil
    },
    ["Drahk Kuva"] = {
        Affinity = 50,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Grineer",
        Family = "Drahk",
        HealthTypes = {["Armure en Ferrite"] = 100, ["Chair"] = 200},
        Icon = nil,
        Image = "KuvaDrahkPH.png",
        Introduced = "19.0",
        Link = nil,
        Name = "Drahk Kuva",
        NameEN = "Kuva Drahk",
        Regions = {"Forteresse Kuva"},
        Scans = 20,
        Weapons = nil
    },
    ["Dreg Lancier"] = {
        Affinity = 50,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Grineer",
        Family = "Dreg Lancier",
        HealthTypes = {["Armure en Ferrite"] = 150, ["Chair Clonée"] = 100},
        Image = "GrnLaserDrone.png",
        Introduced = nil,
        Link = nil,
        Name = "Dreg Lancier",
        NameEN = "Lancer Dreg",
        Regions = {"Terre", "Mars", "Saturne", "Uranus"},
        Scans = 10,
        Weapons = nil
    },
    ["Dreg Temporel"] = {
        Affinity = 57.13,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Grineer",
        Family = "Dreg",
        HealthTypes = {["Armure en Ferrite"] = 150, ["Chair Clonée"] = 100},
        Image = "GrnStasisDrone.png",
        Icon = nil,
        Introduced = nil,
        Link = nil,
        Name = "Dreg Temporel",
        NameEN = "Temporal Dreg",
        Regions = {"Terre", "Saturne", "Uranus"},
        Scans = 10,
        Weapons = nil
    },
    ["Drone d'Attaque"] = {
        Affinity = 200,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Corpus",
        Family = "Drone d'Attaque",
        HealthTypes = {["Robot"] = 250, ["Bouclier"] = 75},
        Image = "FusionDroneDE.png",
        Icon = nil,
        Introduced = nil,
        Link = nil,
        Name = "Drone d'Attaque",
        NameEN = "Attack Drone",
        Regions = {"Mars", "Sedna", "Forteresse Kuva"},
        Scans = 5,
        Weapons = {"Répéteur Plasma"}
    },
    ["Drone d'Attaque (Archwing)"] = {
        Affinity = 57.13,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Corpus",
        HealthTypes = {["Robot"] = 250, ["Bouclier"] = 75},
        Image = "FusionDroneDE.png",
        Icon = nil,
        Introduced = nil,
        Link = nil,
        Name = "Drone d'Attaque (Archwing)",
        NameEN = "Attack Drone (Archwing Enemy)",
        Regions = {"Vénus", "Mars", "Jupiter", "Neptune"},
        Scans = 20,
        Weapons = nil
    },
    ["Drone d'Attaque Terra"] = {
        Affinity = 200,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Corpus",
        Family = "Drone d'Attaque",
        HealthTypes = {["Robot"] = 250, ["Bouclier"] = 75},
        Image = "Drone d'Attaque Terra.png",
        Icon = nil,
        Introduced = nil,
        Link = nil,
        Name = "Drone d'Attaque Terra",
        NameEN = "Terra Attack Drone",
        Regions = {"Vallée Orbis"},
        Scans = 10,
        Weapons = {"Répéteur Plasma"}
    },
    ["Drone Scavenger"] = {
        Affinity = 100,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Corpus",
        Family = "Drone Scavenger",
        HealthTypes = {["Bouclier"] = 50, ["Robot"] = 100},
        Image = "ScavangerOsprey.png",
        Introduced = nil,
        Link = nil,
        Name = "Drone Scavenger",
        NameEN = "Scavenger Drone",
        Regions = {
            "Vénus", "Mars", "Jupiter", "Neptune", "Pluton", "Europe", "Lua"
        },
        Scans = 10,
        Weapons = nil
    },
    -- E
    ["Embatteur MOA Terra"] = {
        Affinity = nil,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Corpus",
        Family = "Embatteur MOA Terra",
        HealthTypes = {["Bouclier"] = 600, ["Robot"] = 600},
        Image = "Embatteur_MOA_Terra.png",
        Introduced = "24.0",
        Link = nil,
        Name = "Embatteur MOA Terra",
        NameEN = "Terra Embattor MOA",
        Regions = {"Vénus"},
        Scans = 3,
        Weapons = nil
    },
    ["Embatteur MOA d'Élite Terra"] = {
        Affinity = nil,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Corpus",
        Family = "Embatteur MOA d'Élite",
        HealthTypes = {["Bouclier"] = 800, ["Robot"] = 1200},
        Image = "TerraEliteEmbattorMOA.png",
        Introduced = "24.0.9",
        Link = nil,
        Name = "Embatteur MOA d'Élite Terra",
        NameEN = "Terra Elite Embattor MOA",
        Regions = {"Vénus"},
        Scans = 3,
        SpawnLevel = 30,
        Weapons = nil
    },
    ["Éviscérateur Exo"] = {
        Affinity = nil,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Grineer",
        Family = "Éviscérateur",
        HealthTypes = {["Armure en Ferrite"] = 200, ["Chair Clonée"] = 400},
        Image = "ExoEviscerator.png",
        Icon = nil,
        Introduced = "27.0",
        Link = nil,
        Name = "Éviscérateur Exo",
        NameEN = "Exo Eviscerator",
        Regions = {"Proxima du Voile"},
        Scans = 5,
        Weapons = {"Grakatas Jumeaux"}
    },
    ["Éviscérateur Gyre"] = {
        Affinity = nil,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Grineer",
        Family = "Éviscérateur",
        HealthTypes = {["Armure en Ferrite"] = 200, ["Chair Clonée"] = 400},
        Image = "GyreEviscerator.png",
        Icon = nil,
        Introduced = "27.0",
        Link = nil,
        Name = "Éviscérateur Gyre",
        NameEN = "Gyre Eviscerator",
        Regions = {"Proxima de Saturne"},
        Scans = 5,
        Weapons = {"Grakatas Jumeaux"}
    },
    ["Éviscérateur Kosma"] = {
        Affinity = nil,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Grineer",
        Family = "Éviscérateur",
        HealthTypes = {["Armure en Ferrite"] = 200, ["Chair Clonée"] = 400},
        Image = "KosmaEviscerator.png",
        Icon = nil,
        Introduced = "27.0",
        Link = nil,
        Name = "Éviscérateur Kosma",
        NameEN = "Kosma Eviscerator",
        Regions = {"Proxima de la Terre"},
        Scans = 5,
        Weapons = {"Grakatas Jumeaux"}
    },
    ["Éviscérateur Pillard Exo"] = {
        Affinity = 150,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Grineer",
        Family = "Éviscérateur Pillard",
        HealthTypes = {["Armure en Ferrite"] = 200, ["Chair Clonée"] = 1000},
        Icon = nil,
        Image = "ExoRaiderEviscerator.png",
        Introduced = "27.0",
        Link = nil,
        Name = "Éviscérateur Pillard Exo",
        NameEN = "Exo Raider Eviscerator",
        Regions = {"Proxima du Voile"},
        Scans = 5,
        Weapons = {"Miter"}
    },
    -- F
    ["Fomorien Balor"] = {
        Affinity = nil,
        BaseLevel = nil,
        Capacities = nil,
        Faction = "Grineer",
        Family = "Fomorien",
        HealthTypes = nil,
        Image = "DEGrineerFomorian.png",
        Icon = nil,
        Introduced = "9.0",
        Link = nil,
        Name = "Fomorien Balor",
        NameEN = "Balor Fomorian",
        Regions = nil,
        Scans = nil,
        SpawnLevel = nil,
        Weapons = nil
    },
    -- G
    ["Garde"] = {
        Affinity = 100,
        BaseLevel = 10,
        Capacities = nil,
        Faction = "Grineer",
        HealthTypes = {["Armure en Ferrite"] = 5, ["Chair Clonée"] = 150},
        Image = "Garde.png",
        Introduced = "13.0",
        Link = nil,
        Name = "Garde",
        NameEN = "Guardsman",
        Regions = {"Cérès", "Sedna", "Deimos"},
        Scans = 10,
        Weapons = {"Amphis"}
    },
    ["Gardien Grineer"] = {
        Affinity = 500,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Grineer",
        HealthTypes = {["Armure en Ferrite"] = 500, ["Chair Clonée"] = 600},
        Image = "DEGrineerWarden.png",
        Icon = nil,
        Introduced = "13.2",
        Link = nil,
        Name = "Gardien Grineer",
        NameEN = "Grineer Warden",
        Regions = {"Cérès"},
        Scans = 3,
        SpawnLevel = nil,
        Weapons = {"Gorgon", "Hind", "Vulkar", "Sheev"}
    },
    ["Général Sargas Ruk"] = {
        Affinity = nil,
        BaseLevel = 1,
        Capacities = {"Grenade Explosive", "Explosion de Feu", "Fournaise"},
        Faction = "Grineer",
        HealthTypes = {["Armure en Alliage"] = 250, ["Chair Clonée"] = 2000},
        Image = "GeneralSargasRukCodex.png",
        Icon = "SargusRuk sigil.png",
        Introduced = "11.0",
        Link = nil,
        Name = "Général Sargas Ruk",
        NameEN = "General Sargas Ruk",
        Regions = {"Saturne"},
        Scans = 3,
        SpawnLevel = 26,
        Weapons = {"Bras Canon"}
    },
    ["Golem Jordas"] = {
        Affinity = nil,
        BaseLevel = 1,
        Capacities = {
            "Canon Laser", "Sphère Électrique", "Vague de Feu",
            "Lanceur de Larves"
        },
        Faction = "Infesté",
        HealthTypes = {["Armure en Ferrite"] = 250, ["Fossilisé"] = 20000},
        Image = "J3Golem.png",
        Icon = nil,
        Introduced = nil,
        Link = nil,
        Name = "Golem Jordas",
        NameEN = "Jordas Golem",
        Regions = {"Eris"},
        Scans = 3,
        SpawnLevel = 34,
        Weapons = nil
    },
    ["Goule Décomposée"] = {
        Affinity = nil,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Grineer",
        Family = "Goule Décomposée",
        HealthTypes = {["Chair Clonée"] = 300, ["Armure en Ferrite"] = 150},
        Image = "GhoulExpired.png",
        Icon = nil,
        Introduced = "22.8",
        Link = nil,
        Name = "Goule Décomposée",
        NameEN = "Ghoul Expired",
        Regions = {"Terre", "Mars"},
        Scans = 20,
        SpawnLevel = nil,
        Weapons = nil
    },
    ["Goule Dévoreuse"] = {
        Affinity = nil,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Grineer",
        Family = "Goule Dévoreuse",
        HealthTypes = {["Armure en Ferrite"] = 250, ["Chair Clonée"] = 600},
        Image = "GhoulDevourer.png",
        Introduced = "22.6",
        Link = nil,
        Name = "Goule Dévoreuse",
        NameEN = "Ghoul Devourer",
        Regions = {"Terre"},
        Scans = 20,
        Weapons = nil
    },
    ["Goule Rictus Alpha"] = {
        Affinity = nil,
        BaseLevel = nil,
        Capacities = nil,
        Faction = "Grineer",
        Family = "Goule Rictus",
        HealthTypes = {["Chair Clonée"] = 1200, ["Armure en Ferrite"] = 250},
        Image = "Goule_Rictus_Alpha.png",
        Icon = nil,
        Introduced = nil,
        Link = nil,
        Name = "Goule Rictus Alpha",
        NameEN = "Ghoul Rictus Alpha",
        Regions = {"Terre"},
        Scans = 3,
        SpawnLevel = nil,
        Weapons = nil
    },
    -- H
    ["Hellion"] = {
        Affinity = 250,
        BaseLevel = 1,
        Capacities = {"Jet-Pack", "Barrage de Missiles"},
        Faction = "Grineer",
        Family = "Hellion",
        HealthTypes = {["Armure en Ferrite"] = 100, ["Chair Clonée"] = 100},
        Image = "Hellion.png",
        Icon = nil,
        Introduced = nil,
        Link = nil,
        Name = "Hellion",
        NameEN = "Hellion",
        Regions = {"Cérès", "Sedna", "Deimos"},
        Scans = 5,
        SpawnLevel = nil,
        Weapons = {"Grakata", "Sheev"}
    },
    ["Hellion Aride"] = {
        Affinity = 250,
        BaseLevel = 1,
        Capacities = {"Jet-Pack", "Barrage de Missiles"},
        Faction = "Grineer",
        Family = "Hellion",
        HealthTypes = {["Armure en Ferrite"] = 100, ["Chair Clonée"] = 180},
        Image = "HellionAride.png",
        Icon = nil,
        Introduced = nil,
        Link = nil,
        Name = "Hellion Aride",
        NameEN = "Arid Hellion",
        Regions = {"Colonie Grineer"},
        Scans = 5,
        SpawnLevel = nil,
        Weapons = {"Grakata", "Sheev"}
    },
    ["Hellion Dargyn-Blindé"] = {
        Affinity = 150,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Grineer",
        Family = "Hellion Dargyn-Blindé",
        HealthTypes = {["Armure en Ferrite"] = 200, ["Chair Clonée"] = 300},
        Icon = nil,
        Image = "GrnSkiffMissileShield.png",
        Introduced = nil,
        Link = nil,
        Name = "Hellion Dargyn-Blindé",
        NameEN = "Shield-Hellion Dargyn",
        Regions = {"Uranus"},
        Scans = 5,
        SpawnLevel = nil,
        Weapons = nil
    },
    ["Hemocyte"] = {
        Affinity = 725.31,
        BaseLevel = 10,
        Capacities = nil,
        Faction = "Infesté",
        Family = nil,
        HealthTypes = {["Chair Fossilisée"] = 2200, ["Tendon Infesté"] = 175},
        Image = "Hémocyte.png",
        Icon = nil,
        Introduced = nil,
        Link = nil,
        Name = "Hemocyte",
        NameEN = "Hemocyte",
        Regions = {"Terre"},
        Scans = 3,
        SpawnLevel = nil,
        Weapons = nil
    },
    ["Homme d'Équipage"] = {
        Affinity = 57.13,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Corpus",
        Family = "Homme d'Équipage",
        HealthTypes = {["Chair"] = 60, ["Bouclier"] = 150},
        Image = "CrewmanNormal.png",
        Icon = nil,
        Introduced = nil,
        Link = nil,
        Name = "Homme d'Équipage",
        NameEN = "Crewman",
        Regions = {"Vénus", "Mars", "Jupiter", "Phobos", "Europe"},
        Scans = 20,
        SpawnLevel = nil,
        Weapons = {"Dera", "Prova"}
    },
    ["Homme d'Équipage d'Élite Juno"] = {
        Affinity = nil,
        BaseLevel = 16,
        Capacities = nil,
        Faction = "Corpus",
        Family = "Homme d'Équipage d'Élite",
        HealthTypes = {["Bouclier"] = 200, ["Chair"] = 100},
        Image = nil,
        Introduced = "28.0",
        Link = nil,
        Name = "Homme d'Équipage d'Élite Juno",
        NameEN = "Juno Elite Crewman",
        Regions = nil,
        Scans = 5,
        Weapons = {"Supra"}
    },
    ["Homme d'Équipage Prod"] = {
        Affinity = 57.13,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Corpus",
        Family = "Homme d'Équipage Prod",
        HealthTypes = {["Bouclier"] = 50, ["Chair"] = 100},
        Image = "250px-CrewmanProd.png",
        Icon = nil,
        Introduced = nil,
        Link = nil,
        Name = "Homme d'Équipage Prod",
        NameEN = "Prod Crewman",
        Regions = {"Vénus", "Mars", "Deimos"},
        Scans = 20,
        SpawnLevel = nil,
        Weapons = {"Prova"}
    },
    ["Hyena Cinderthresh"] = {
        Affinity = nil,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Corpus",
        Family = "Hyena",
        HealthTypes = {
            ["Armure en Alliage"] = 50,
            ["Proto-Bouclier"] = 500,
            ["Robot"] = 800
        },
        Image = "CinderthreshHyena.png",
        Introduced = "24.0",
        Link = nil,
        Name = "Hyena Cinderthresh",
        NameEN = "Cinderthresh Hyena",
        Regions = {"Vénus"},
        Scans = 3,
        SpawnLevel = nil,
        Weapons = nil
    },
    ["Hyena Gyre"] = {
        Affinity = nil,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Corpus",
        Family = "Hyena",
        HealthTypes = {
            ["Armure en Alliage"] = 25,
            ["Proto-Bouclier"] = 500,
            ["Robot"] = 800
        },
        Image = "GyreHyena.png",
        Introduced = "24.0",
        Link = nil,
        Name = "Hyena Gyre",
        NameEN = "Gyre Hyena",
        Regions = {"Vénus"},
        Scans = 3,
        SpawnLevel = nil,
        Weapons = nil
    },
    ["Hyena Icemire"] = {
        Affinity = nil,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Corpus",
        Family = "Hyena",
        HealthTypes = {
            ["Armure en Alliage"] = 25,
            ["Proto-Bouclier"] = 500,
            ["Robot"] = 800
        },
        Image = "IcemireHyena.png",
        Introduced = "24.0",
        Link = nil,
        Name = "Hyena Icemire",
        NameEN = "Icemire Hyena",
        Regions = {"Vénus"},
        Scans = 3,
        SpawnLevel = nil,
        Weapons = nil
    },
    ["Hyena Rabbleback"] = {
        Affinity = nil,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Corpus",
        Family = "Hyena",
        HealthTypes = {
            ["Armure en Alliage"] = 25,
            ["Proto-Bouclier"] = 500,
            ["Robot"] = 800
        },
        Image = "RabblebackHyena.png",
        Introduced = "24.0",
        Link = nil,
        Name = "Hyena Rabbleback",
        NameEN = "Rabbleback Hyena",
        Regions = {"Vénus"},
        Scans = 3,
        SpawnLevel = nil,
        Weapons = nil
    },
    -- I
    -- J
    ["Jackal"] = {
        Affinity = 1500,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Corpus",
        Family = "Jackal",
        HealthTypes = {
            ["Armure en Alliage"] = 100,
            ["Proto-Bouclier"] = 2000,
            ["Robot"] = 1500
        },
        Icon = "Jackal sigil.png",
        Image = "Jackal_2020.png",
        Introduced = "Vanilla",
        Link = nil,
        Name = "Jackal",
        NameEN = "Jackal",
        Regions = {"Vénus"},
        Scans = 3,
        SpawnLevel = 8,
        Weapons = {"Mitrailleuses Lourdes"}
    },
    ["Jackal Terra"] = {
        Affinity = nil,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Corpus",
        Family = "Jackal",
        HealthTypes = {
            ["Armure en Alliage"] = 100,
            ["Proto-Bouclier"] = 3000,
            ["Robot"] = 3000
        },
        Image = nil,
        Introduced = "24.0",
        Link = nil,
        Name = "Jackal Terra",
        NameEN = "Terra Jackal",
        Regions = {"Vénus"},
        Scans = 3,
        SpawnLevel = 19,
        Weapons = {"Mitrailleuses Lourdes"}
    },
    ["Jugulus Deimos"] = {
        Affinity = nil,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Infesté",
        Family = "Jugulus",
        HealthTypes = {["Chair Fossilisée"] = 1600, ["Tendon Infesté"] = 300},
        Image = "Jugulus Deimos.png",
        Icon = nil,
        Introduced = "29.0",
        Link = nil,
        Name = "Jugulus Deimos",
        NameEN = "Deimos Jugulus",
        Regions = {"Deimos"},
        Scans = 5,
        SpawnLevel = nil,
        Weapons = nil
    },
    -- K
    ["Kavat Sauvage"] = {
        Affinity = nil,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Non-affilié",
        Family = "Kavat Sauvage",
        HealthTypes = {["Armure en Ferrite"] = 175, ["Chair"] = 300},
        Image = "FeralCatbrow.png",
        Introduced = "18.5",
        Link = nil,
        Name = "Kavat Sauvage",
        NameEN = "Feral Kavat",
        Regions = {"Deimos"},
        Scans = 20,
        Weapons = nil
    },
    ["Kubrow Sauvage"] = {
        Affinity = 50,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Non-affilié",
        Family = "Kubrow Sauvage",
        HealthTypes = {["Armure en Ferrite"] = 200, ["Chair"] = 300},
        Icon = nil,
        Image = "KubrowSauvage.png",
        Introduced = "13.3",
        Link = nil,
        Name = "Kubrow Sauvage",
        NameEN = "Feral Kubrow",
        Regions = {"Terre"},
        Scans = 20,
        SpawnLevel = nil,
        Weapons = nil
    },
    -- L
    ["Lancier"] = {
        Affinity = 50,
        BaseLevel = 1,
        Capacities = {"Grenade à Plasma"},
        Faction = "Grineer",
        Family = "Lancier",
        HealthTypes = {["Armure en Ferrite"] = 100, ["Chair Clonée"] = 100},
        Image = "Lancier.png",
        Icon = nil,
        Introduced = nil,
        Link = nil,
        Name = "Lancier",
        NameEN = "Lancer",
        Regions = {"Mercure", "Terre", "Mars", "Cérès", "Deimos"},
        Scans = 20,
        SpawnLevel = nil,
        Weapons = {"Grakata", "Sheev"}
    },
    ["Lancier Aride"] = {
        Affinity = 50,
        BaseLevel = 1,
        Capacities = {"Grenade à Plasma"},
        Faction = "Grineer",
        Family = "Lancier",
        HealthTypes = {["Armure en Ferrite"] = 100, ["Chair Clonée"] = 100},
        Image = "DesertRifleLancerAvatar.png",
        Icon = nil,
        Introduced = nil,
        Link = nil,
        Name = "Lancier Aride",
        NameEN = "Arid Lancer",
        Regions = {"Mars", "Deimos"},
        Scans = 20,
        SpawnLevel = nil,
        Weapons = {"Grakata", "Sheev"}
    },
    ["Lancier Drekar"] = {
        Affinity = 50,
        BaseLevel = 1,
        Capacities = {"Grenade à Plasma"},
        Faction = "Grineer",
        Family = "Lancier",
        HealthTypes = {["Armure en Ferrite"] = 100, ["Chair Clonée"] = 100},
        Image = "LancierDrekar.png",
        Icon = nil,
        Introduced = "17.0",
        Link = nil,
        Name = "Lancier Drekar",
        NameEN = "Drekar Lancer",
        Regions = {"Terre", "Uranus"},
        Scans = 20,
        SpawnLevel = nil,
        Weapons = {"Grakata", "Sheev"}
    },
    ["Lancier d'Élite"] = {
        Affinity = 150,
        BaseLevel = 15,
        Capacities = {"Grenade à Plasma"},
        Faction = "Grineer",
        Family = "Lancier d'Élite",
        HealthTypes = {["Armure en Alliage"] = 200, ["Chair Clonée"] = 150},
        Image = "Lancier_Elite.png",
        Icon = nil,
        Introduced = "9.0",
        Link = nil,
        Name = "Lancier d'Élite",
        NameEN = "Elite Lancer",
        Regions = {"Mercure", "Saturne", "Cérès", "Sedna", "Deimos", "Lua"},
        Scans = 5,
        SpawnLevel = nil,
        Weapons = {"Hind", "Sheev"}
    },
    ["Lancier d'Élite Gyre"] = {
        Affinity = 150,
        BaseLevel = 15,
        Capacities = nil,
        Faction = "Grineer",
        Family = "Lancier d'Élite",
        HealthTypes = {["Armure en Ferrite"] = 200, ["Chair Clonée"] = 1000},
        Icon = nil,
        Image = "GyreEliteLancer.png",
        Introduced = nil,
        Link = nil,
        Name = "Lancier d'Élite Gyre",
        NameEN = "Gyre Elite Lancer",
        Regions = {"Proxima de Saturne"},
        Scans = 5,
        SpawnLevel = nil,
        Weapons = {"Quartakk"}
    },
    ["Lancier Frontalier"] = {
        Affinity = 50,
        BaseLevel = 1,
        Capacities = {"Grenade à Plasma"},
        Faction = "Grineer",
        Family = "Lancier",
        HealthTypes = {["Armure en Ferrite"] = 100, ["Chair Clonée"] = 100},
        Image = "ForestLancer.png",
        Icon = nil,
        Introduced = nil,
        Link = nil,
        Name = "Lancier Frontalier",
        NameEN = "Frontier Lancer",
        Regions = {"Terre"},
        Scans = 20,
        SpawnLevel = nil,
        Weapons = {"Grakata", "Sheev"}
    },
    ["Lancier Ivoire"] = {
        Affinity = 50,
        BaseLevel = 1,
        Capacities = {"Grenade à Plasma"},
        Faction = "Grineer",
        Family = "Lancier",
        HealthTypes = {["Armure en Ferrite"] = 100, ["Chair Clonée"] = 100},
        Image = "EidolonRifleLancer.png",
        Icon = nil,
        Introduced = "22.0",
        Link = nil,
        Name = "Lancier Ivoire",
        NameEN = "Tusk Lancer",
        Regions = {"Terre"},
        Scans = 20,
        SpawnLevel = nil,
        Weapons = {"Hind", "Sheev"}
    },
    ["Lancier Kuva"] = {
        Affinity = 50,
        BaseLevel = 1,
        Capacities = {"Grenade à Plasma"},
        Faction = "Grineer",
        Family = "Lancier",
        HealthTypes = {["Armure en Ferrite"] = 100, ["Chair Clonée"] = 100},
        Image = "KuvaLancer.png",
        Icon = nil,
        Introduced = "19.0",
        Link = nil,
        Name = "Lancier Kuva",
        NameEN = "Kuva Lancer",
        Regions = {"Forteresse Kuva"},
        Scans = 20,
        SpawnLevel = nil,
        Weapons = {"Kohm", "Sheev"}
    },
    ["Lancier Nightwatch"] = {
        Affinity = 50,
        BaseLevel = 1,
        Capacities = {"Grenade à Plasma"},
        Faction = "Grineer",
        Family = "Lancier",
        HealthTypes = {["Armure en Ferrite"] = 100, ["Chair Clonée"] = 100},
        Image = "Lancier Nightwatch.png",
        Icon = nil,
        Introduced = nil,
        Link = nil,
        Name = "Lancier Nightwatch",
        NameEN = "Nightwatch Lancer",
        Regions = {"Alerte Tactique"},
        Scans = 20,
        SpawnLevel = nil,
        Weapons = {"Grinlok", "Sheev"}
    },
    ["Larve"] = {
        Affinity = 35,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Infesté",
        Family = "Larve",
        HealthTypes = {["Infesté"] = 20},
        Icon = nil,
        Image = "250px-Larve.png",
        Introduced = "15.5",
        Link = "Larve (Ennemi)",
        Name = "Larve",
        NameEN = "Maggot",
        Regions = {"Eris"},
        Scans = 30,
        SpawnLevel = nil,
        Weapons = nil
    },
    ["Latcher"] = {
        Affinity = 100,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Grineer",
        Family = "Latcher",
        HealthTypes = {["Armure en Ferrite"] = 100, ["Machines"] = 1},
        Image = "Latcher.png",
        Introduced = nil,
        Link = nil,
        Name = "Latcher",
        NameEN = "Latcher",
        Regions = nil,
        Scans = 10,
        SpawnLevel = nil,
        Weapons = nil
    },
    ["Leekter"] = {
        Affinity = nil,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Grineer",
        Family = "Leekter",
        HealthTypes = {["Armure en Alliage"] = 200, ["Chair Clonée"] = 1700},
        Image = "DELeekter.png",
        Introduced = nil,
        Link = "Le_Trio_Grustrag#Leekter",
        Name = "Leekter",
        NameEN = "Leekter",
        Regions = nil,
        Scans = 3,
        Weapons = {"Manticore"}
    },
    ["Lephantis"] = {
        Affinity = 3998.75,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Infesté",
        Family = nil,
        HealthTypes = {["Fossilisé"] = 1200},
        Image = "Lephantis.png",
        Icon = nil,
        Introduced = "10.0",
        Link = nil,
        Name = "Lephantis",
        NameEN = "Lephantis",
        Regions = {"Deimos"},
        Scans = 3,
        SpawnLevel = nil,
        Weapons = nil
    },
    ["Lieutenant Lech Kril"] = {
        Affinity = nil,
        BaseLevel = 1,
        Capacities = {"Vague de Glace", "Vague de Feu", "Barrière de Flammes"},
        Faction = "Grineer",
        Family = "Lieutenant Lech Kril",
        HealthTypes = {
            ["Armure en Alliage"] = 250,
            ["Bouclier"] = 400,
            ["Chair Clonée"] = 4000
        },
        Icon = "LechKril_sigil.png",
        Image = "LechKril.png",
        Introduced = nil,
        Link = nil,
        Name = "Lieutenant Lech Kril",
        NameEN = "Lieutenant Lech Kril",
        Regions = {"Mars"},
        Scans = 3,
        SpawnLevel = 13,
        Weapons = {"Gorgon", "Brokk"}
    },
    ["Loup de Saturne Six"] = {
        Affinity = nil,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Non-affilié",
        Family = "Loup de Saturne Six",
        HealthTypes = {["Armure en Alliage"] = 200, ["Machines"] = 1500},
        Image = "Loup de Saturne Six Sentient.png",
        Introduced = "24.3",
        Link = nil,
        Name = "Loup de Saturne Six",
        NameEN = "Wolf of Saturn Six",
        Regions = nil,
        Scans = 3,
        Weapons = {"Marteau du Loup"}
    },
    -- M
    ["Marteleur Ivoire"] = {
        Affinity = 500,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Grineer",
        Family = "Marteleur Ivoire",
        HealthTypes = {["Armure en Alliage"] = 100, ["Machines"] = 3000},
        Icon = nil,
        Image = "Marteleur_Ivoire.png",
        Introduced = "24.6",
        Link = nil,
        Name = "Marteleur Ivoire",
        NameEN = "Tusk Thumper",
        Regions = {"Terre"},
        Scans = 3,
        SpawnLevel = 20,
        Weapons = nil
    },
    ["Marteleur Taureau Ivoire"] = {
        Affinity = 500,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Grineer",
        Family = "Marteleur Ivoire",
        HealthTypes = {["Armure en Alliage"] = 100, ["Machines"] = 4000},
        Icon = nil,
        Image = "Marteleur_Taureau_Ivoire.png",
        Introduced = "24.6",
        Link = nil,
        Name = "Marteleur Taureau Ivoire",
        NameEN = "Tusk Thumper Bull",
        Regions = {"Terre"},
        Scans = 3,
        SpawnLevel = 30,
        Weapons = nil
    },
    ["Marteleur Doma Ivoire"] = {
        Affinity = 500,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Grineer",
        Family = "Marteleur Ivoire",
        HealthTypes = {["Armure en Alliage"] = 100, ["Machines"] = 5000},
        Icon = nil,
        Image = "Marteleur_Doma_Ivoire.png",
        Introduced = "24.6",
        Link = nil,
        Name = "Marteleur Doma Ivoire",
        NameEN = "Tusk Thumper Doma",
        Regions = {"Terre"},
        Scans = 3,
        SpawnLevel = 30,
        Weapons = nil
    },
    ["Massacreur Drekar"] = {
        Affinity = 50,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Grineer",
        Family = "Massacreur",
        HealthTypes = {["Armure en Ferrite"] = 5, ["Chair Clonée"] = 50},
        Image = "Massacreur Drekar.png",
        Icon = nil,
        Introduced = "17.0",
        Link = nil,
        Name = "Massacreur Drekar",
        NameEN = "Drekar Butcher",
        Regions = {"Uranus"},
        Scans = 20,
        SpawnLevel = nil,
        Weapons = {"Doubles Hachoir"}
    },
    ["Massacreur Gyre"] = {
        Affinity = nil,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Grineer",
        Family = "Massacreur",
        HealthTypes = {["Armure en Ferrite"] = 200, ["Chair Clonée"] = 750},
        Icon = nil,
        Image = "GyreButcher.png",
        Introduced = "27.0",
        Link = nil,
        Name = "Massacreur Gyre",
        NameEN = "Gyre Butcher",
        Regions = {"Proxima de Saturne"},
        Scans = 20,
        SpawnLevel = nil,
        Weapons = {"Machette"}
    },
    ["Massacreur Kosma"] = {
        Affinity = nil,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Grineer",
        Family = "Massacreur",
        HealthTypes = {["Chair Clonée"] = 750, ["Armure en Ferrite"] = 200},
        Image = "Massacreur Kosma.png",
        Icon = nil,
        Introduced = "27.0",
        Link = nil,
        Name = "Massacreur Kosma",
        NameEN = "Kosma Butcher",
        Regions = {"Proxima de la Terre"},
        Scans = 20,
        SpawnLevel = nil,
        Weapons = {"Machette"}
    },
    ["Mesa Infestée"] = {
        Affinity = 1713.75,
        BaseLevel = 1,
        Capacities = {
            "{{A|Batterie Balistique}}", "{{A|Salle de tir}}",
            "{{A|Bouclier Scélérat}}", "{{A|Pacificateurs}}"
        },
        Faction = "Infesté",
        Family = nil,
        HealthTypes = {
            ["Chair"] = 1700,
            ["Armure en Ferrite"] = 200,
            ["Bouclier"] = 1000
        },
        Image = "Mesa_Infesté.png",
        Icon = nil,
        Introduced = nil,
        Link = nil,
        Name = "Mesa Infestée",
        NameEN = "Infested Mesa",
        Regions = {"Eris"},
        Scans = 1,
        SpawnLevel = nil,
        Weapons = {"Pacificateurs", "Épée à Plasma"}
    },
    ["Messager Fanatique"] = {
        Affinity = nil,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Infesté",
        Family = "Fanatique",
        HealthTypes = {["Tendon Infesté"] = 200, ["Chair Infestée"] = 1000},
        Image = "MessagerFanatique.png",
        Icon = nil,
        Introduced = "25.3",
        Link = nil,
        Name = "Messager Fanatique",
        NameEN = "Zealot Proselytizer",
        Regions = nil,
        Scans = 5,
        SpawnLevel = nil,
        Weapons = {"Torid"}
    },
    ["Meute Hyena"] = {
        Affinity = 1500,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Corpus",
        Family = "Hyena",
        HealthTypes = {
            ["Armure en Alliage"] = 25,
            ["Proto-Bouclier"] = 1000,
            ["Robot"] = 800
        },
        Icon = "HyenaPack_sigil.png",
        Image = "HyenaPack.png",
        Introduced = nil,
        Link = nil,
        Name = "Meute Hyena",
        NameEN = "Hyena Pack",
        Regions = {"Neptune"},
        Scans = 3,
        SpawnLevel = nil,
        Weapons = nil
    },
    ["MOA à Canon Électrique"] = {
        Affinity = 114.25,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Corpus",
        Family = "MOA à Canon Électrique",
        HealthTypes = {["Bouclier"] = 150, ["Robot"] = 60},
        Image = "MoaRailgun.png",
        Icon = nil,
        Introduced = nil,
        Link = nil,
        Name = "MOA à Canon Électrique",
        NameEN = "Railgun MOA",
        Regions = {
            "Vénus", "Mars", "Neptune", "Pluton", "Europe", "Le Néant", "Lua"
        },
        Scans = 10,
        SpawnLevel = nil,
        Weapons = {"Canon Électrique"}
    },
    ["MOA à Canon Électrique Terra"] = {
        Affinity = nil,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Corpus",
        Family = "MOA à Canon Électrique",
        HealthTypes = {["Bouclier"] = 0, ["Robot"] = 0},
        Image = nil,
        Icon = nil,
        Introduced = "24.0",
        Link = nil,
        Name = "MOA à Canon Électrique Terra",
        NameEN = "Terra Railgun MOA",
        Regions = {"Vénus"},
        Scans = 10,
        SpawnLevel = nil,
        Weapons = {"Canon Électrique"}
    },
    ["MOA Cible"] = {
        Affinity = nil,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Corpus",
        Family = "MOA Cible",
        HealthTypes = {["Bouclier"] = 0, ["Robot"] = 0},
        Image = "Popcorn.png",
        Introduced = "28.0",
        Link = nil,
        Name = "MOA Cible",
        NameEN = "Test MOA",
        Regions = {"Vénus"},
        Scans = 3,
        SpawnLevel = nil,
        Weapons = nil
    },
    ["MOA Corrompu"] = {
        Affinity = 200,
        BaseLevel = 1,
        Capacities = {"Déploiement de {{Pet|Drone Corrompu}}"},
        Faction = "Orokin",
        Family = "MOA Corrompu",
        HealthTypes = {["Bouclier"] = 250, ["Robot"] = 250},
        Image = "OrokinMoaBipedAvatar.png",
        Icon = nil,
        Introduced = nil,
        Link = nil,
        Name = "MOA Corrompu",
        NameEN = "Corrupted MOA",
        Regions = {"Le Néant"},
        Scans = 5,
        SpawnLevel = nil,
        Weapons = {"Rayon à Plasma"}
    },
    ["MOA Geminex Juno"] = {
        Affinity = nil,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Corpus",
        Family = "MOA Geminex",
        HealthTypes = {["Bouclier"] = 200, ["Robot"] = 60},
        Image = "JunoGeminexMOA.png",
        Introduced = "28.0",
        Link = nil,
        Name = "MOA Geminex Juno",
        NameEN = "Juno Geminex MOA",
        Regions = {"Vénus", "Jupiter", "Neptune", "Pluton", "Europe", "Phobos"},
        Scans = 5,
        Weapons = nil
    },
    ["MOA Mutaliste Essaim"] = {
        Affinity = 150,
        BaseLevel = 12,
        Capacities = {"Onde de Choc"},
        Faction = "Infesté",
        Family = "MOA Mutaliste Essaim",
        HealthTypes = {["Fossilisé"] = 350},
        Image = "MOA-Essaim.png",
        Icon = nil,
        Introduced = nil,
        Link = nil,
        Name = "MOA Mutaliste Essaim",
        NameEN = "Swarm Mutalist MOA",
        Regions = {
            "Mercure", "Vénus", "Terre", "Mars", "Jupiter", "Saturne",
            "Uranus", "Neptune", "Pluton", "Cérès", "Éris", "Sedna",
            "Europe", "Phobos", "Deimos"
        },
        Scans = 5,
        SpawnLevel = nil,
        Weapons = {"Spores Infestées"}
    },
    ["MOA Onde de Choc"] = {
        Affinity = 200,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Corpus",
        Family = "MOA Onde de Choc",
        HealthTypes = {["Bouclier"] = 150, ["Robot"] = 60},
        Image = "MoaShockwave.png",
        Introduced = nil,
        Link = nil,
        Name = "MOA Onde de Choc",
        NameEN = "Shockwave MOA",
        Regions = {
            "Vénus", "Mars", "Neptune", "Pluton", "Europe", "Deimos", "Lua"
        },
        Scans = 5,
        Weapons = nil
    },
    ["MOA Onde de Choc Terra"] = {
        Affinity = 200,
        BaseLevel = 15,
        Capacities = nil,
        Faction = "Corpus",
        Family = "MOA Onde de Choc",
        HealthTypes = {["Bouclier"] = 200, ["Robot"] = 200},
        Image = "TerraShockwaveMOA.png",
        Introduced = "24.0",
        Link = nil,
        Name = "MOA Onde de Choc Terra",
        NameEN = "Terra Shockwave MOA",
        Regions = {"Vénus"},
        Scans = 5,
        Weapons = nil
    },
    ["MOA Onde de Choc Vapos"] = {
        Affinity = nil,
        BaseLevel = 15,
        Capacities = nil,
        Faction = "Corpus",
        Family = "MOA Onde de Choc",
        HealthTypes = {["Bouclier"] = 150, ["Robot"] = 60},
        Image = "VaposShockwaveMoa.png",
        Introduced = "25.0",
        Link = nil,
        Name = "MOA Onde de Choc Vapos",
        NameEN = "Vapos Shockwave MOA",
        Regions = {"Jupiter"},
        Scans = 5,
        Weapons = nil
    },
    ["MOA Terra"] = {
        Affinity = nil,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Corpus",
        Family = "MOA",
        HealthTypes = {["Bouclier"] = 150, ["Robot"] = 60},
        Image = "MOA_Terra.png",
        Introduced = "24.0",
        Link = nil,
        Name = "MOA Terra",
        NameEN = "Terra MOA",
        Regions = {"Vénus"},
        Scans = 10,
        Weapons = nil
    },
    -- N
    ["Napalm"] = {
        Affinity = 674.53,
        BaseLevel = 6,
        Capacities = nil,
        Faction = "Grineer",
        Family = "Napalm",
        HealthTypes = {["Chair Clonée"] = 600, ["Armure en Alliage"] = 500},
        Image = "Napalm.png",
        Icon = nil,
        Introduced = nil,
        Link = nil,
        Name = "Napalm",
        NameEN = "Napalm",
        Regions = {"Mercure", "Mars", "Cérès", "Saturne", "Uranus", "Sedna"},
        Scans = 5,
        SpawnLevel = nil,
        Weapons = {"Sheev", "Ogris"}
    },
    ["Nemes"] = {
        Affinity = nil,
        BaseLevel = 1,
        Capacities = {"Kamikaze"},
        Faction = "Corpus",
        Family = "Nemes",
        HealthTypes = {["Bouclier"] = 150, ["Robot"] = 750},
        Image = "Nemes.png",
        Introduced = "18.4.1",
        Link = nil,
        Name = "Nemes",
        NameEN = "Nemes",
        Regions = nil,
        Scans = 5,
        SpawnLevel = 5,
        Weapons = nil
    },
    ["Nox"] = {
        Affinity = 500,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Grineer",
        Family = "Nox",
        HealthTypes = {["Armure en Alliage"] = 250, ["Chair Clonée"] = 350},
        Image = "NoxTemp.png",
        Introduced = "21.0",
        Link = nil,
        Name = "Nox",
        NameEN = "Nox",
        Regions = {
            "Mercure", "Terre", "Saturne", "Cérès", "Sedna", "Le Néant",
            "Deimos"
        },
        Scans = 3,
        Weapons = nil
    },
    -- O
    ["Officier Gokstad Kosma"] = {
        Affinity = 500,
        BaseLevel = 8,
        Capacities = nil,
        Faction = "Grineer",
        Family = "Officier Gokstad",
        HealthTypes = {["Chair Clonée"] = 1000, ["Armure en Ferrite"] = 1000},
        Image = "KosmaGokstadOfficer.png",
        Icon = nil,
        Introduced = "27.0",
        Link = nil,
        Name = "Officier Gokstad",
        NameEN = "Gokstad Officer",
        Regions = nil,
        Scans = 3,
        SpawnLevel = nil,
        Weapons = {"Karak Wraith"}
    },
    ["Orbis Preneur de Profit"] = {
        Affinity = 0,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Corpus",
        Family = "Orbis",
        HealthTypes = {
            ["Robotique"] = 372505,
            ["Armure en Alliage"] = 1092,
            ["Bouclier"] = 813225
        },
        Image = "Orbis_Preneur_de_Profit.png",
        Icon = nil,
        Introduced = "24.0",
        Link = nil,
        Name = "Orbis Preneur de Profit",
        NameEN = "Profit-Taker Orb",
        Regions = {"Vallée Orbis"},
        Scans = 3,
        SpawnLevel = 60,
        Weapons = nil
    },
    ["Osprey Oxium"] = {
        Affinity = 150,
        BaseLevel = 5,
        Capacities = {"Kamikaze"},
        Faction = "Corpus",
        Family = "Osprey Oxium",
        HealthTypes = {
            ["Armure en Ferrite"] = 40,
            ["Bouclier"] = 150,
            ["Robot"] = 750
        },
        Image = "OspreySuicide.png",
        Introduced = "11.9",
        Link = nil,
        Name = "Osprey Oxium",
        NameEN = "Oxium Osprey",
        Regions = {
            "Vénus", "Mars", "Jupiter", "Neptune", "Pluton", "Eris", "Europe",
            "Lua"
        },
        Scans = 20,
        Weapons = nil
    },
    ["Osprey Oxium Juno"] = {
        Affinity = 150,
        BaseLevel = 5,
        Capacities = {"Kamikaze"},
        Faction = "Corpus",
        Family = "Osprey Oxium",
        HealthTypes = {
            ["Armure en Ferrite"] = 40,
            ["Bouclier"] = 150,
            ["Robot"] = 750
        },
        Image = "JunoOxiumOsprey.png",
        Introduced = "28.0",
        Link = nil,
        Name = "Osprey Oxium Juno",
        NameEN = "Juno Oxium Osprey",
        Regions = nil,
        Scans = 5,
        Weapons = nil
    },
    ["Osprey Oxium Terra"] = {
        Affinity = nil,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Corpus",
        Family = "Osprey Oxium",
        HealthTypes = {
            ["Armure en Ferrite"] = 0,
            ["Bouclier"] = 0,
            ["Robot"] = 0
        },
        Image = nil,
        Introduced = "24.0",
        Link = nil,
        Name = "Osprey Oxium Terra",
        NameEN = "Terra Oxium Osprey",
        Regions = {"Vénus"},
        Scans = 5,
        Weapons = nil
    },
    ["Osprey Oxium Vapos"] = {
        Affinity = 150,
        BaseLevel = 5,
        Capacities = {"Kamikaze"},
        Faction = "Corpus",
        Family = "Osprey Oxium",
        HealthTypes = {
            ["Armure en Ferrite"] = 40,
            ["Bouclier"] = 150,
            ["Robot"] = 750
        },
        Image = "VaposOxiumOsprey.png",
        Introduced = "25.0",
        Link = nil,
        Name = "Osprey Oxium Vapos",
        NameEN = "Vapos Oxium Osprey",
        Regions = nil,
        Scans = 5,
        Weapons = nil
    },
    ["Osprey Protecteur Terra"] = {
        Affinity = nil,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Corpus",
        Family = "Osprey Protecteur",
        HealthTypes = {["Bouclier"] = 50, ["Robot"] = 35},
        Image = "TerraShieldOsprey.png",
        Introduced = "24.0",
        Link = nil,
        Name = "Osprey Protecteur Terra",
        NameEN = "Terra Shield Osprey",
        Regions = {"Vénus"},
        Scans = 5,
        Weapons = nil
    },
    ["Osprey Sangsue"] = {
        Affinity = 100,
        BaseLevel = 15,
        Capacities = nil,
        Faction = "Corpus",
        Family = "Osprey Sangsue",
        HealthTypes = {["Bouclier"] = 50, ["Robot"] = 100},
        Image = "LeechOspreyDE.png",
        Icon = nil,
        Introduced = "Vanilla",
        Link = nil,
        Name = "Osprey Sangsue",
        NameEN = "Leech Osprey",
        Regions = {"Neptune", "Pluton", "Europe", "Le Néant", "Lua"},
        Scans = 10,
        SpawnLevel = nil,
        Weapons = nil
    },
    ["Osprey Sapeur"] = {
        Affinity = 150,
        BaseLevel = 15,
        Capacities = nil,
        Faction = "Corpus",
        Family = "Osprey Sapeur",
        HealthTypes = {["Bouclier"] = 50, ["Robot"] = 200},
        Image = "SapeurOsprey.png",
        Icon = nil,
        Introduced = nil,
        Link = nil,
        Name = "Osprey Sapeur",
        NameEN = "Sapping Osprey",
        Regions = {"Jupiter", "Neptune", "Pluton", "Europe", "Lua"},
        Scans = 5,
        SpawnLevel = nil,
        Weapons = nil
    },
    ["Osprey Sapeur Vapos"] = {
        Affinity = nil,
        BaseLevel = 15,
        Capacities = nil,
        Faction = "Corpus",
        Family = "Osprey Sapeur",
        HealthTypes = {["Bouclier"] = 50, ["Robot"] = 80},
        Image = "VaposSappingOsprey.png",
        Icon = nil,
        Introduced = "25.0",
        Link = nil,
        Name = "Osprey Sapeur Vapos",
        NameEN = "Vapos Sapping Osprey",
        Regions = {"Jupiter"},
        Scans = 5,
        SpawnLevel = nil,
        Weapons = nil
    },
    -- P
    ["Phorid"] = {
        Affinity = 3500,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Infesté",
        Family = "Phorid",
        HealthTypes = {["Armure en Ferrite"] = 25, ["Fossilisé"] = 5000},
        Icon = "Phorid_sigil.png",
        Image = "PhoridDE2.png",
        Introduced = "6.0",
        Link = nil,
        Name = "Phorid",
        NameEN = "Phorid",
        Regions = nil,
        Scans = 3,
        Weapons = nil
    },
    ["Pillard Exo"] = {
        Affinity = 150,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Grineer",
        Family = "Pillard",
        HealthTypes = {["Armure en Ferrite"] = 200, ["Chair Clonée"] = 1000},
        Icon = nil,
        Image = "ExoRaider.png",
        Introduced = "27.0",
        Link = nil,
        Name = "Pillard Exo",
        NameEN = "Exo Raider",
        Regions = {"Proxima du Voile"},
        Scans = 5,
        SpawnLevel = nil,
        Weapons = {"Tonkor"}
    },
    ["Pilote de Gokstad Kosma"] = {
        Affinity = 50,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Grineer",
        Family = "Pilote de Gokstad",
        HealthTypes = {["Armure en Ferrite"] = 200, ["Chair Clonée"] = 600},
        Icon = nil,
        Image = "KosmaGokstadPilot.png",
        Introduced = "27.0",
        Link = nil,
        Name = "Pilote de Gokstad Kosma",
        NameEN = "Kosma Gokstad Pilot",
        Regions = {"Proxima de la Terre"},
        Scans = 20,
        SpawnLevel = nil,
        Weapons = {"Stubba"}
    },
    ["Prélat Zéloïde"] = {
        Affinity = nil,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Infesté",
        Family = "Prélat Zéloïde",
        HealthTypes = {["Infesté"] = 11000},
        Image = "ZealoidPrelate.png",
        Introduced = "25.7.7",
        Link = nil,
        Name = "Prélat Zéloïde",
        NameEN = "Zealoid Prelate",
        Regions = {"Deimos"},
        Scans = 3,
        Weapons = {"Pathocyst"}
    },
    ["Prosélyte Fanatique"] = {
        Affinity = nil,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Infesté",
        Family = "Prosélyte Fanatique",
        HealthTypes = {["Tendon Infesté"] = 200, ["Chair Infestée"] = 1200},
        Image = "Prosélyte_Fanatique.png",
        Icon = nil,
        Introduced = "25.3",
        Link = nil,
        Name = "Prosélyte Fanatique",
        NameEN = "Zealot Proselytizer",
        Regions = nil,
        Scans = 5,
        SpawnLevel = nil,
        Weapons = {"Zymos"}
    },
    -- Q
    -- R
    ["Raie du Désert"] = {
        Affinity = 50,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Non-affilié",
        Family = nil,
        HealthTypes = {["Chair"] = 250, ["Armure en Ferrite"] = 200},
        Image = "Raie du Désert.png",
        Icon = nil,
        Introduced = nil,
        Link = nil,
        Name = "Raie du Désert",
        NameEN = "Desert Skate",
        Regions = nil,
        Scans = 20,
        Weapons = nil
    },
    ["Raknoïde Kyta"] = {
        Affinity = 1500,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Corpus",
        Family = "Raknoïde Kyta",
        HealthTypes = {
            ["Armure en Alliage"] = 150,
            ["Proto-Bouclier"] = 10000,
            ["Robot"] = 4000
        },
        Image = "Raknoid Kyta.png",
        Introduced = "24.0",
        Link = nil,
        Name = "Raknoïde Kyta",
        NameEN = "Kyta Raknoid",
        Regions = {"Vénus"},
        Scans = 3,
        Weapons = nil
    },
    ["Raknoïde Mite"] = {
        Affinity = nil,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Corpus",
        Family = "Raknoïde Mite",
        HealthTypes = {
            ["Armure en Ferrite"] = 0,
            ["Bouclier"] = 0,
            ["Robot"] = 0
        },
        Image = "MiteRaknoid.png",
        Introduced = "24.0",
        Link = nil,
        Name = "Raknoïde Mite",
        NameEN = "Mite Raknoid",
        Regions = {"Vénus"},
        Scans = 5,
        Weapons = nil
    },
    ["Raknoïde Réfrigérant"] = {
        Affinity = 300,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Corpus",
        Family = "Raknoïde Thermique",
        HealthTypes = {
            ["Robot"] = 100,
            ["Armure en Alliage"] = 250,
            ["Proto-Bouclier"] = 2000
        },
        Icon = nil,
        Image = "Raknoïde_Réfrigérant.png",
        Introduced = "24.4",
        Link = nil,
        Name = "Raknoïde Réfrigérant",
        NameEN = "Coolant Raknoid",
        Regions = {"Vénus"},
        Scans = 5,
        SpawnLevel = 50,
        Weapons = nil
    },
    ["Raknoïde Scyto"] = {
        Affinity = 1000,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Corpus",
        Family = "Raknoïde Scyto",
        HealthTypes = {["Robot"] = 5000, ["Armure en Alliage"] = 200},
        Icon = nil,
        Image = "Raknoïde_Scyto.png",
        Introduced = "24.0",
        Link = nil,
        Name = "Raknoïde Réfrigérant",
        NameEN = "Scyto Raknoid",
        Regions = {"Vénus"},
        Scans = 3,
        SpawnLevel = nil,
        Weapons = nil
    },
    ["Rampant Nauséeux"] = {
        Affinity = 57.13,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Infesté",
        Family = "Rampant Nauséeux",
        HealthTypes = {["Chair Infesté"] = 50},
        Image = "Rampant Nauséeux.png",
        Icon = nil,
        Introduced = "10.5",
        Link = nil,
        Name = "Rampant Nauséeux",
        NameEN = "Nauseous Crawler",
        Regions = {"Vénus", "Terre", "Mars", "Jupiter", "Saturne", "Eris"},
        Scans = 20,
        Weapons = nil
    },
    ["Rampant Électrique"] = {
        Affinity = 57.13,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Infesté",
        Family = "Rampant Électrique",
        HealthTypes = {["Chair Infesté"] = 50},
        Image = "Rampant_Électrique.png",
        Icon = nil,
        Introduced = "10.5",
        Link = nil,
        Name = "Rampant Électrique",
        NameEN = "Electric Crawler",
        Regions = {
            "Mercure", "Mars", "Deimos", "Phobos", "Jupiter", "Europe",
            "Saturne", "Uranus", "Neptune", "Pluton", "Eris", "Sedna"
        },
        Scans = 20,
        Weapons = nil
    },
    ["Raptor SX d'Élite Terra"] = {
        Affinity = nil,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Corpus",
        Family = "Raptor SX d'Élite",
        HealthTypes = {["Bouclier"] = 1750, ["Robot"] = 1750},
        Image = "TerraEliteRaptorSX.png",
        Introduced = "24.0.9",
        Link = nil,
        Name = "Raptor SX d'Élite Terra",
        NameEN = "Terra Elite Raptor SX",
        Regions = {"Vénus"},
        Scans = 3,
        SpawnLevel = 30,
        Weapons = nil
    },
    ["Raptor SX Terra"] = {
        Affinity = nil,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Corpus",
        Family = "Raptor SX",
        HealthTypes = {
            ["Armure en Ferrite"] = 50,
            ["Bouclier"] = 1000,
            ["Robot"] = 750
        },
        Image = "Raptor SX Terra.png",
        Introduced = "24.0",
        Link = nil,
        Name = "Raptor SX Terra",
        NameEN = "Terra Raptor SX",
        Regions = {"Vénus"},
        Scans = 3,
        Weapons = nil
    },
    ["Régulateur"] = {
        Affinity = 50,
        BaseLevel = 1,
        Capacities = {"Booster de Moral", "Brouilleur de Radar"},
        Faction = "Grineer",
        Family = "Régulateur",
        HealthTypes = {["Armure en Ferrite"] = 200, ["Machines"] = 120},
        Image = "Regulateur.png",
        Introduced = nil,
        Link = nil,
        Name = "Régulateur",
        NameEN = "Regulator",
        Regions = {"Mars"},
        Scans = 20,
        Weapons = nil
    },
    ["Régulateur de Capteur"] = {
        Affinity = 50,
        BaseLevel = 1,
        Capacities = {"Camera de Surveillance"},
        Faction = "Grineer",
        Family = "Régulateur de Capteur",
        HealthTypes = {["Armure en Ferrite"] = 300, ["Machines"] = 100},
        Image = "Regulateur.png",
        Introduced = nil,
        Link = nil,
        Name = "Régulateur de Capteur",
        NameEN = "Sensor Regulator",
        Regions = {
            "Mercure", "Terre", "Mars", "Saturne", "Uranus", "Cérès", "Sedna",
            "Phobos"
        },
        Scans = 20,
        Weapons = nil
    },
    ["Régulateur Frontalier"] = {
        Affinity = 50,
        BaseLevel = 1,
        Capacities = {"Booster de Moral", "Brouilleur de Radar"},
        Faction = "Grineer",
        Family = "Régulateur",
        HealthTypes = {["Armure en Ferrite"] = 200, ["Machines"] = 120},
        Image = "Regulateur.png",
        Introduced = "11.5",
        Link = nil,
        Name = "Régulateur Frontalier",
        NameEN = "Frontier Regulator",
        Regions = {"Terre"},
        Scans = 20,
        Weapons = nil
    },
    ["Roller"] = {
        Affinity = 100,
        BaseLevel = 10,
        Capacities = nil,
        Faction = "Grineer",
        Family = "Roller",
        HealthTypes = {["Armure en Ferrite"] = 100, ["Machines"] = 40},
        Image = "RollingDroneAvatar.png",
        Introduced = nil,
        Link = nil,
        Name = "Roller",
        NameEN = "Roller",
        Regions = {
            "Mars", "Saturne", "Uranus", "Cérès", "Sedna", "Le Néant",
            "Deimos"
        },
        Scans = 10,
        Weapons = nil
    },
    ["Roller Ivoire"] = {
        Affinity = 100,
        BaseLevel = 10,
        Capacities = nil,
        Faction = "Grineer",
        Family = "Roller",
        HealthTypes = {["Armure en Ferrite"] = 100, ["Machines"] = 60},
        Image = "EidolonRollingDrone.png",
        Introduced = nil,
        Link = nil,
        Name = "Roller Ivoire",
        NameEN = "Tusk Roller",
        Regions = {"Terre"},
        Scans = 10,
        Weapons = nil
    },
    ["Roller Kuva"] = {
        Affinity = 100,
        BaseLevel = 10,
        Capacities = nil,
        Faction = "Grineer",
        Family = "Roller",
        HealthTypes = {["Armure en Ferrite"] = 100, ["Machines"] = 40},
        Image = "KuvaRoller.png",
        Introduced = nil,
        Link = nil,
        Name = "Roller Kuva",
        NameEN = "Kuva Roller",
        Regions = {"Forteresse Kuva"},
        Scans = 10,
        Weapons = nil
    },
    ["Roller Sentinelle"] = {
        Affinity = nil,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Grineer",
        Family = "Roller Sentinelle",
        HealthTypes = {["Armure en Ferrite"] = 100, ["Machines"] = 200},
        Image = "RollerTurret.png",
        Introduced = "18.10",
        Link = nil,
        Name = "Roller Sentinelle",
        NameEN = "Roller Sentry",
        Regions = nil,
        Scans = 10,
        Weapons = nil
    },
    ["Ropalolyste"] = {
        Affinity = nil,
        BaseLevel = 17,
        Capacities = {
            "Lasers", "Hurlement Zéro", "Flux Électrique", "Laser Géant",
            "Missiles à Têtes Chercheuses", "Attrape"
        },
        Faction = "Sentient",
        Family = "Ropalolyste",
        HealthTypes = {
            ["Armure en Alliage"] = 200,
            ["Bouclier"] = 2000,
            ["Robot"] = 5000
        },
        Image = "Ropalolyst.png",
        Icon = nil,
        Introduced = "25.0",
        Link = nil,
        Name = "Ropalolyste",
        NameEN = "Ropalolyste",
        Regions = {"Jupiter"},
        Scans = 3,
        Weapons = nil
    },
    -- S
    ["Sauteur Lourdaud"] = {
        Affinity = nil,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Infesté",
        Family = "Sauteur Lourdaud",
        HealthTypes = {["Chair Infesté"] = 600},
        Image = "Sauteur Lourdaud.png",
        Icon = nil,
        Introduced = "25.7.3.1",
        Link = nil,
        Name = "Sauteur Lourdaud",
        NameEN = "Leaping Thrasher",
        Regions = {"Deimos"},
        Scans = 5,
        Weapons = nil
    },
    ["Sauteur Lourdaud Deimos"] = {
        Affinity = nil,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Infesté",
        Family = "Sauteur Lourdaud",
        HealthTypes = {["Chair Infesté"] = 600},
        Image = "Sauteur Lourdaud Deimos.png",
        Icon = nil,
        Introduced = "29.0",
        Link = nil,
        Name = "Sauteur Lourdaud Deimos",
        NameEN = "Deimos Leaping Thrasher",
        Regions = {"Deimos"},
        Scans = 5,
        Weapons = nil
    },
    ["Scorpion"] = {
        Affinity = 145.06,
        BaseLevel = 10,
        Capacities = {"Ligne d'Arrachage"},
        Faction = "Grineer",
        Family = "Scorpion",
        HealthTypes = {["Armure en Ferrite"] = 150, ["Chair Clonée"] = 150},
        Image = "250px-ScorpionDE.png",
        Icon = nil,
        Introduced = "8.0",
        Link = nil,
        Name = "Scorpion",
        NameEN = "Scorpion",
        Regions = {
            "Mercure", "Terre", "Mars", "Saturne", "Cérès", "Sedna",
            "Le Néant", "Deimos", "Lua"
        },
        Scans = 10,
        Weapons = {"Machette"}
    },
    ["Scorpion Kuva"] = {
        Affinity = 100.00,
        BaseLevel = 10,
        Capacities = nil,
        Faction = "Grineer",
        Family = "Scorpion",
        HealthTypes = {["Chair Clonée"] = 150, ["Armure en Ferrite"] = 150},
        Image = "Scorpion Kuva.png",
        Icon = nil,
        Introduced = "19.0",
        Link = nil,
        Name = "Scorpion Kuva",
        NameEN = "Kuva Scorpion",
        Regions = {"Forteresse Kuva"},
        Scans = 10,
        Weapons = {"Machette"}
    },
    ["Shik Tal"] = {
        Affinity = 1500,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Grineer",
        Family = "Shik Tal",
        HealthTypes = {["Armure en Alliage"] = 200, ["Chair Clonée"] = 1700},
        Image = "DEShik.png",
        Introduced = nil,
        Link = nil,
        Name = "Shik Tal",
        NameEN = "Shik Tal",
        Regions = nil,
        Scans = 3,
        Weapons = {"Marelok", "Bouclier Antiémeute"}
    },
    ["Sikula"] = {
        Affinity = 114.25,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Grineer",
        Family = nil,
        HealthTypes = {
            ["Machines"] = 100,
            ["Armure en Ferrite"] = 50,
            ["Bouclier"] = 50
        },
        Image = "Sikula.png",
        Icon = nil,
        Introduced = "17.0",
        Link = nil,
        Name = "Sikula",
        NameEN = "Sikula",
        Regions = {"Uranus"},
        Scans = 10,
        Weapons = nil
    },
    ["Spectre Orphid"] = {
        Affinity = nil,
        BaseLevel = nil,
        Capacities = {"{{A|Spores}}", "{{A|Mue}}", "{{A|Miasme}}"},
        Faction = "Orokin",
        Family = nil,
        HealthTypes = {
            ["Chair"] = 1500,
            ["Armure en Ferrite"] = 200,
            ["Bouclier"] = 1000
        },
        Image = "Orphid.png",
        Icon = nil,
        Introduced = nil,
        Link = nil,
        Name = "Spectre Orphid",
        NameEN = "Orphid Specter",
        Regions = {"Terre"},
        Scans = 1,
        SpawnLevel = nil,
        Weapons = {"Zhuge"}
    },
    ["Spectre Orphid (mue)"] = {
        Affinity = nil,
        BaseLevel = nil,
        Capacities = nil,
        Faction = "Orokin",
        Family = nil,
        HealthTypes = {
            ["Chair"] = 1500,
            ["Armure en Ferrite"] = 200,
            ["Bouclier"] = 1000
        },
        Image = "Orphid.png",
        Icon = nil,
        Introduced = nil,
        Link = "Spectre Orphid",
        Name = "Spectre Orphid (mue)",
        NameEN = "Orphid Specter",
        Regions = {"Terre"},
        Scans = nil,
        SpawnLevel = nil,
        Weapons = nil
    },
    ["Spectre (Tenno)"] = {
        Affinity = nil,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Tenno",
        Family = nil,
        HealthTypes = {
            ["Chair"] = 200,
            ["Armure en Ferrite"] = 20,
            ["Bouclier"] = 80
        },
        Image = "Spectre Tenno.png",
        Icon = nil,
        Introduced = "SotR",
        Link = nil,
        Name = "Spectre ()Tenno)",
        NameEN = "Tenno Specter",
        Regions = {
            "Terre", "Venus", "Mars", "Ceres", "Jupiter", "Saturne", "Uranus",
            "Neptune", "Pluton"
        },
        Scans = 1,
        SpawnLevel = nil,
        Weapons = nil
    },
    ["Stalker"] = {
        Affinity = 1713.75,
        BaseLevel = 1,
        Capacities = {
            "Élan Tranchant", "Téléportation", "Absorption", "Attraction",
            "Écran de Fumée", "Jugement"
        },
        Faction = "Stalker",
        Family = "Stalker",
        HealthTypes = {
            ["Armure en Alliage"] = 300,
            ["Chair"] = 450,
            ["Proto-Bouclier"] = 200
        },
        Image = "Stalker_cdx.png",
        Icon = "StalkerSigil.png",
        Introduced = "7.0",
        Link = nil,
        Name = "Stalker",
        NameEN = "Stalker",
        Regions = {"Toutes"},
        Scans = 3,
        Weapons = {"Dread", "Despair", "Hate"}
    },
    ["Stalker de l'Ombre"] = {
        Affinity = 1713.75,
        BaseLevel = 1,
        Capacities = {"Charge Rhino", "Lame Exaltée", "Attraction"},
        Faction = "Stalker",
        Family = "Stalker",
        HealthTypes = {
            ["Chair"] = 750,
            ["Armure en Alliage"] = 300,
            ["Proto-Bouclier"] = 200
        },
        Image = "SentientStalker.png",
        Icon = nil,
        Introduced = "18.0",
        Link = nil,
        Name = "Stalker de l'Ombre",
        NameEN = "Shadow Stalker",
        Regions = nil,
        Scans = 3,
        SpawnLevel = nil,
        Weapons = {"War"}
    },
    ["Suppresseur Exo"] = {
        Affinity = 150,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Grineer",
        Family = "Suppresseur",
        HealthTypes = {["Armure en Ferrite"] = 200, ["Chair Clonée"] = 500},
        Image = "ExoSupressor.png",
        Icon = nil,
        Introduced = "27.0",
        Link = nil,
        Name = "Suppresseur Exo",
        NameEN = "Exo Supressor",
        Regions = {"Proxima du Voile"},
        Scans = 5,
        Weapons = {"Lance-glace"}
    },
    ["Suppresseur Gyre"] = {
        Affinity = 150,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Grineer",
        Family = "Suppresseur",
        HealthTypes = {["Armure en Ferrite"] = 200, ["Chair Clonée"] = 500},
        Icon = nil,
        Image = "GyreSupressor.png",
        Introduced = "27.0",
        Link = nil,
        Name = "Suppresseur Gyre",
        NameEN = "Gyre Supressor",
        Regions = {"Proxima de Saturne"},
        Scans = 5,
        Weapons = {"Lance-glace"}
    },
    ["Suppresseur Kosma"] = {
        Affinity = 150,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Grineer",
        Family = "Suppresseur",
        HealthTypes = {["Armure en Ferrite"] = 200, ["Chair Clonée"] = 500},
        Image = "KosmaSupressor.png",
        Icon = nil,
        Introduced = "27.0",
        Link = nil,
        Name = "Suppresseur Kosma",
        NameEN = "Kosma Supressor",
        Regions = {"Proxima de la Terre"},
        Scans = 5,
        Weapons = {"Lance-glace"}
    },
    -- T
    ["Teralyste Eidolon"] = {
        Affinity = 1003.81,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Sentient",
        Family = "Eidolon",
        HealthTypes = {
            ["Robotique"] = 333135,
            ["Armure en Alliage"] = 692.18,
            ["Bouclier"] = 28511.25
        },
        Image = "Teralyst.png",
        Icon = nil,
        Introduced = 15.0,
        Link = nil,
        Name = "Teralyste Eidolon",
        NameEN = "Eidolon Teralyst",
        Regions = {"Terre"},
        Scans = 3,
        SpawnLevel = 50,
        Weapons = nil
    },
    ["Tourelle Senta"] = {
        Affinity = 50,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Corpus",
        Family = "Tourelle Senta",
        HealthTypes = {["Armure en Ferrite"] = 100, ["Robot"] = 300},
        Image = "TourelleCorpus.png",
        Icon = nil,
        Introduced = "5.0",
        Link = "Tourelle",
        Name = "Tourelle Senta",
        NameEN = "Senta Turret",
        Regions = nil,
        Scans = 20,
        Weapons = {"Répéteur Plasma"}
    },
    ["Tourelle Osprey Terra"] = {
        Affinity = nil,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Corpus",
        Family = "Tourelle Osprey",
        HealthTypes = {["Bouclier"] = 0, ["Robot"] = 0},
        Image = nil,
        Introduced = nil,
        Link = nil,
        Name = "Tourelle Osprey Terra",
        NameEN = "Terra Turret Osprey",
        Regions = nil,
        Scans = nil,
        Weapons = nil
    },
    ["Trio Raptors"] = {
        Affinity = 1500,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Corpus",
        Family = "Trio Raptors",
        HealthTypes = {
            ["Armure en Alliage"] = 0,
            ["Proto-Bouclier"] = 0,
            ["Robot"] = 0
        },
        Icon = "Raptor_sigil.png",
        Image = nil,
        Introduced = "9.0",
        Link = nil,
        Name = "Trio Raptors",
        NameEN = "Raptors",
        Regions = {"Europe"},
        Scans = 3,
        Weapons = nil
    },
    ["Tyl Regor"] = {
        Affinity = 1500,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Grineer",
        Family = "Tyl Regor",
        HealthTypes = {
            ["Armure en Alliage"] = 250,
            ["Bouclier"] = 800,
            ["Chair Clonée"] = 3000
        },
        Icon = "TylRegor_sigil.png",
        Image = "NewTylRegor.png",
        Introduced = "5.0",
        Link = nil,
        Name = "Tyl Regor",
        NameEN = "Tyl Regor",
        Regions = {"Uranus"},
        Scans = 3,
        Weapons = {"Ack & Brunt", "Knux"}
    },
    -- U
    -- V
    ["Vem Tabook"] = {
        Affinity = 1500,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Grineer",
        Family = "Vem Tabook",
        HealthTypes = {["Armure en Alliage"] = 200, ["Chair Clonée"] = 1700},
        Image = "DETabook.png",
        Introduced = nil,
        Link = nil,
        Name = "Vem Tabook",
        NameEN = "Vem Tabook",
        Regions = nil,
        Scans = 3,
        Weapons = {"Hek"}
    },
    ["Voltigeur"] = {
        Affinity = 35,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Infesté",
        Family = "Voltigeur",
        HealthTypes = {["Infesté"] = 100},
        Image = "Sauteur.png",
        Introduced = nil,
        Name = "Voltigeur",
        NameEN = "Leaper",
        Regions = {
            "Mercure", "Vénus", "Terre", "Mars", "Jupiter", "Saturne",
            "Uranus", "Neptune", "Cérès", "Éris", "Sedna", "Europe",
            "Phobos", "Deimos"
        },
        Scans = 30,
        Weapons = nil
    },
    ["Voltigeur Deimos"] = {
        Affinity = nil,
        BaseLevel = nil,
        Capacities = nil,
        Faction = "Infesté",
        Family = "Voltigeur",
        HealthTypes = {["Chair Infesté"] = nil},
        Image = "Voltigeur Deimos.png",
        Icon = nil,
        Introduced = 29.0,
        Link = nil,
        Name = "Voltigeur Deimos",
        NameEN = "Deimos Leaper",
        Regions = {"Deimos"},
        Scans = 30,
        SpawnLevel = nil,
        Weapons = nil
    },
    -- W
    -- X
    -- Y
    -- Z
    ["Zeplen"] = {
        Affinity = 2000,
        BaseLevel = 1,
        Capacities = nil,
        Faction = "Grineer",
        Family = nil,
        HealthTypes = {["Armure en Ferrite"] = 2750, ["Chair Clonée"] = 400},
        Image = "GrnMissilePlatform.png",
        Icon = nil,
        Introduced = nil,
        Link = nil,
        Name = "Zeplen",
        NameEN = "Zeplen",
        Regions = nil,
        Scans = 3,
        Weapons = nil
    }
}

return EnemyData
